// This file has been automatically generated by `objc2`'s `header-translator`.
// DO NOT EDIT

//! # Bindings to the `Virtualization` framework
#![allow(unused_imports)]
#![allow(deprecated)]
#![allow(non_snake_case)]
#![allow(non_camel_case_types)]
#![allow(non_upper_case_globals)]
#![allow(missing_docs)]
#![allow(clippy::too_many_arguments)]
#![allow(clippy::type_complexity)]
#![allow(clippy::upper_case_acronyms)]
#![allow(clippy::identity_op)]
#![allow(clippy::missing_safety_doc)]

#[link(name = "Virtualization", kind = "framework")]
extern "C" {}

#[cfg(feature = "Virtualization_VZAudioDeviceConfiguration")]
#[path = "VZAudioDeviceConfiguration.rs"]
mod __VZAudioDeviceConfiguration;
#[cfg(feature = "Virtualization_VZAudioInputStreamSource")]
#[path = "VZAudioInputStreamSource.rs"]
mod __VZAudioInputStreamSource;
#[cfg(feature = "Virtualization_VZAudioOutputStreamSink")]
#[path = "VZAudioOutputStreamSink.rs"]
mod __VZAudioOutputStreamSink;
#[cfg(feature = "Virtualization_VZBootLoader")]
#[path = "VZBootLoader.rs"]
mod __VZBootLoader;
#[cfg(feature = "Virtualization_VZBridgedNetworkDeviceAttachment")]
#[path = "VZBridgedNetworkDeviceAttachment.rs"]
mod __VZBridgedNetworkDeviceAttachment;
#[cfg(feature = "Virtualization_VZBridgedNetworkInterface")]
#[path = "VZBridgedNetworkInterface.rs"]
mod __VZBridgedNetworkInterface;
#[cfg(feature = "Virtualization_VZConsoleDevice")]
#[path = "VZConsoleDevice.rs"]
mod __VZConsoleDevice;
#[cfg(feature = "Virtualization_VZConsoleDeviceConfiguration")]
#[path = "VZConsoleDeviceConfiguration.rs"]
mod __VZConsoleDeviceConfiguration;
#[cfg(feature = "Virtualization_VZConsolePortConfiguration")]
#[path = "VZConsolePortConfiguration.rs"]
mod __VZConsolePortConfiguration;
#[cfg(feature = "Virtualization_VZDefines")]
#[path = "VZDefines.rs"]
mod __VZDefines;
#[cfg(feature = "Virtualization_VZDirectoryShare")]
#[path = "VZDirectoryShare.rs"]
mod __VZDirectoryShare;
#[cfg(feature = "Virtualization_VZDirectorySharingDevice")]
#[path = "VZDirectorySharingDevice.rs"]
mod __VZDirectorySharingDevice;
#[cfg(feature = "Virtualization_VZDirectorySharingDeviceConfiguration")]
#[path = "VZDirectorySharingDeviceConfiguration.rs"]
mod __VZDirectorySharingDeviceConfiguration;
#[cfg(feature = "Virtualization_VZDiskBlockDeviceStorageDeviceAttachment")]
#[path = "VZDiskBlockDeviceStorageDeviceAttachment.rs"]
mod __VZDiskBlockDeviceStorageDeviceAttachment;
#[cfg(feature = "Virtualization_VZDiskImageStorageDeviceAttachment")]
#[path = "VZDiskImageStorageDeviceAttachment.rs"]
mod __VZDiskImageStorageDeviceAttachment;
#[cfg(feature = "Virtualization_VZDiskSynchronizationMode")]
#[path = "VZDiskSynchronizationMode.rs"]
mod __VZDiskSynchronizationMode;
#[cfg(feature = "Virtualization_VZEFIBootLoader")]
#[path = "VZEFIBootLoader.rs"]
mod __VZEFIBootLoader;
#[cfg(feature = "Virtualization_VZEFIVariableStore")]
#[path = "VZEFIVariableStore.rs"]
mod __VZEFIVariableStore;
#[cfg(feature = "Virtualization_VZEntropyDeviceConfiguration")]
#[path = "VZEntropyDeviceConfiguration.rs"]
mod __VZEntropyDeviceConfiguration;
#[cfg(feature = "Virtualization_VZError")]
#[path = "VZError.rs"]
mod __VZError;
#[cfg(feature = "Virtualization_VZFileHandleNetworkDeviceAttachment")]
#[path = "VZFileHandleNetworkDeviceAttachment.rs"]
mod __VZFileHandleNetworkDeviceAttachment;
#[cfg(feature = "Virtualization_VZFileHandleSerialPortAttachment")]
#[path = "VZFileHandleSerialPortAttachment.rs"]
mod __VZFileHandleSerialPortAttachment;
#[cfg(feature = "Virtualization_VZFileSerialPortAttachment")]
#[path = "VZFileSerialPortAttachment.rs"]
mod __VZFileSerialPortAttachment;
#[cfg(feature = "Virtualization_VZGenericMachineIdentifier")]
#[path = "VZGenericMachineIdentifier.rs"]
mod __VZGenericMachineIdentifier;
#[cfg(feature = "Virtualization_VZGenericPlatformConfiguration")]
#[path = "VZGenericPlatformConfiguration.rs"]
mod __VZGenericPlatformConfiguration;
#[cfg(feature = "Virtualization_VZGraphicsDevice")]
#[path = "VZGraphicsDevice.rs"]
mod __VZGraphicsDevice;
#[cfg(feature = "Virtualization_VZGraphicsDeviceConfiguration")]
#[path = "VZGraphicsDeviceConfiguration.rs"]
mod __VZGraphicsDeviceConfiguration;
#[cfg(feature = "Virtualization_VZGraphicsDisplay")]
#[path = "VZGraphicsDisplay.rs"]
mod __VZGraphicsDisplay;
#[cfg(feature = "Virtualization_VZGraphicsDisplayConfiguration")]
#[path = "VZGraphicsDisplayConfiguration.rs"]
mod __VZGraphicsDisplayConfiguration;
#[cfg(feature = "Virtualization_VZHostAudioInputStreamSource")]
#[path = "VZHostAudioInputStreamSource.rs"]
mod __VZHostAudioInputStreamSource;
#[cfg(feature = "Virtualization_VZHostAudioOutputStreamSink")]
#[path = "VZHostAudioOutputStreamSink.rs"]
mod __VZHostAudioOutputStreamSink;
#[cfg(feature = "Virtualization_VZKeyboardConfiguration")]
#[path = "VZKeyboardConfiguration.rs"]
mod __VZKeyboardConfiguration;
#[cfg(feature = "Virtualization_VZLinuxBootLoader")]
#[path = "VZLinuxBootLoader.rs"]
mod __VZLinuxBootLoader;
#[cfg(feature = "Virtualization_VZLinuxRosettaAbstractSocketCachingOptions")]
#[path = "VZLinuxRosettaAbstractSocketCachingOptions.rs"]
mod __VZLinuxRosettaAbstractSocketCachingOptions;
#[cfg(feature = "Virtualization_VZLinuxRosettaCachingOptions")]
#[path = "VZLinuxRosettaCachingOptions.rs"]
mod __VZLinuxRosettaCachingOptions;
#[cfg(feature = "Virtualization_VZLinuxRosettaDirectoryShare")]
#[path = "VZLinuxRosettaDirectoryShare.rs"]
mod __VZLinuxRosettaDirectoryShare;
#[cfg(feature = "Virtualization_VZLinuxRosettaUnixSocketCachingOptions")]
#[path = "VZLinuxRosettaUnixSocketCachingOptions.rs"]
mod __VZLinuxRosettaUnixSocketCachingOptions;
#[cfg(feature = "Virtualization_VZMACAddress")]
#[path = "VZMACAddress.rs"]
mod __VZMACAddress;
#[cfg(feature = "Virtualization_VZMacAuxiliaryStorage")]
#[path = "VZMacAuxiliaryStorage.rs"]
mod __VZMacAuxiliaryStorage;
#[cfg(feature = "Virtualization_VZMacGraphicsDevice")]
#[path = "VZMacGraphicsDevice.rs"]
mod __VZMacGraphicsDevice;
#[cfg(feature = "Virtualization_VZMacGraphicsDeviceConfiguration")]
#[path = "VZMacGraphicsDeviceConfiguration.rs"]
mod __VZMacGraphicsDeviceConfiguration;
#[cfg(feature = "Virtualization_VZMacGraphicsDisplay")]
#[path = "VZMacGraphicsDisplay.rs"]
mod __VZMacGraphicsDisplay;
#[cfg(feature = "Virtualization_VZMacGraphicsDisplayConfiguration")]
#[path = "VZMacGraphicsDisplayConfiguration.rs"]
mod __VZMacGraphicsDisplayConfiguration;
#[cfg(feature = "Virtualization_VZMacHardwareModel")]
#[path = "VZMacHardwareModel.rs"]
mod __VZMacHardwareModel;
#[cfg(feature = "Virtualization_VZMacKeyboardConfiguration")]
#[path = "VZMacKeyboardConfiguration.rs"]
mod __VZMacKeyboardConfiguration;
#[cfg(feature = "Virtualization_VZMacMachineIdentifier")]
#[path = "VZMacMachineIdentifier.rs"]
mod __VZMacMachineIdentifier;
#[cfg(feature = "Virtualization_VZMacOSBootLoader")]
#[path = "VZMacOSBootLoader.rs"]
mod __VZMacOSBootLoader;
#[cfg(feature = "Virtualization_VZMacOSConfigurationRequirements")]
#[path = "VZMacOSConfigurationRequirements.rs"]
mod __VZMacOSConfigurationRequirements;
#[cfg(feature = "Virtualization_VZMacOSInstaller")]
#[path = "VZMacOSInstaller.rs"]
mod __VZMacOSInstaller;
#[cfg(feature = "Virtualization_VZMacOSRestoreImage")]
#[path = "VZMacOSRestoreImage.rs"]
mod __VZMacOSRestoreImage;
#[cfg(feature = "Virtualization_VZMacOSVirtualMachineStartOptions")]
#[path = "VZMacOSVirtualMachineStartOptions.rs"]
mod __VZMacOSVirtualMachineStartOptions;
#[cfg(feature = "Virtualization_VZMacPlatformConfiguration")]
#[path = "VZMacPlatformConfiguration.rs"]
mod __VZMacPlatformConfiguration;
#[cfg(feature = "Virtualization_VZMacTrackpadConfiguration")]
#[path = "VZMacTrackpadConfiguration.rs"]
mod __VZMacTrackpadConfiguration;
#[cfg(feature = "Virtualization_VZMemoryBalloonDevice")]
#[path = "VZMemoryBalloonDevice.rs"]
mod __VZMemoryBalloonDevice;
#[cfg(feature = "Virtualization_VZMemoryBalloonDeviceConfiguration")]
#[path = "VZMemoryBalloonDeviceConfiguration.rs"]
mod __VZMemoryBalloonDeviceConfiguration;
#[cfg(feature = "Virtualization_VZMultipleDirectoryShare")]
#[path = "VZMultipleDirectoryShare.rs"]
mod __VZMultipleDirectoryShare;
#[cfg(feature = "Virtualization_VZNATNetworkDeviceAttachment")]
#[path = "VZNATNetworkDeviceAttachment.rs"]
mod __VZNATNetworkDeviceAttachment;
#[cfg(feature = "Virtualization_VZNVMExpressControllerDeviceConfiguration")]
#[path = "VZNVMExpressControllerDeviceConfiguration.rs"]
mod __VZNVMExpressControllerDeviceConfiguration;
#[cfg(feature = "Virtualization_VZNetworkBlockDeviceStorageDeviceAttachment")]
#[path = "VZNetworkBlockDeviceStorageDeviceAttachment.rs"]
mod __VZNetworkBlockDeviceStorageDeviceAttachment;
#[cfg(feature = "Virtualization_VZNetworkDevice")]
#[path = "VZNetworkDevice.rs"]
mod __VZNetworkDevice;
#[cfg(feature = "Virtualization_VZNetworkDeviceAttachment")]
#[path = "VZNetworkDeviceAttachment.rs"]
mod __VZNetworkDeviceAttachment;
#[cfg(feature = "Virtualization_VZNetworkDeviceConfiguration")]
#[path = "VZNetworkDeviceConfiguration.rs"]
mod __VZNetworkDeviceConfiguration;
#[cfg(feature = "Virtualization_VZPlatformConfiguration")]
#[path = "VZPlatformConfiguration.rs"]
mod __VZPlatformConfiguration;
#[cfg(feature = "Virtualization_VZPointingDeviceConfiguration")]
#[path = "VZPointingDeviceConfiguration.rs"]
mod __VZPointingDeviceConfiguration;
#[cfg(feature = "Virtualization_VZSerialPortAttachment")]
#[path = "VZSerialPortAttachment.rs"]
mod __VZSerialPortAttachment;
#[cfg(feature = "Virtualization_VZSerialPortConfiguration")]
#[path = "VZSerialPortConfiguration.rs"]
mod __VZSerialPortConfiguration;
#[cfg(feature = "Virtualization_VZSharedDirectory")]
#[path = "VZSharedDirectory.rs"]
mod __VZSharedDirectory;
#[cfg(feature = "Virtualization_VZSingleDirectoryShare")]
#[path = "VZSingleDirectoryShare.rs"]
mod __VZSingleDirectoryShare;
#[cfg(feature = "Virtualization_VZSocketDevice")]
#[path = "VZSocketDevice.rs"]
mod __VZSocketDevice;
#[cfg(feature = "Virtualization_VZSocketDeviceConfiguration")]
#[path = "VZSocketDeviceConfiguration.rs"]
mod __VZSocketDeviceConfiguration;
#[cfg(feature = "Virtualization_VZSpiceAgentPortAttachment")]
#[path = "VZSpiceAgentPortAttachment.rs"]
mod __VZSpiceAgentPortAttachment;
#[cfg(feature = "Virtualization_VZStorageDeviceAttachment")]
#[path = "VZStorageDeviceAttachment.rs"]
mod __VZStorageDeviceAttachment;
#[cfg(feature = "Virtualization_VZStorageDeviceConfiguration")]
#[path = "VZStorageDeviceConfiguration.rs"]
mod __VZStorageDeviceConfiguration;
#[cfg(feature = "Virtualization_VZUSBKeyboardConfiguration")]
#[path = "VZUSBKeyboardConfiguration.rs"]
mod __VZUSBKeyboardConfiguration;
#[cfg(feature = "Virtualization_VZUSBMassStorageDeviceConfiguration")]
#[path = "VZUSBMassStorageDeviceConfiguration.rs"]
mod __VZUSBMassStorageDeviceConfiguration;
#[cfg(feature = "Virtualization_VZUSBScreenCoordinatePointingDeviceConfiguration")]
#[path = "VZUSBScreenCoordinatePointingDeviceConfiguration.rs"]
mod __VZUSBScreenCoordinatePointingDeviceConfiguration;
#[cfg(feature = "Virtualization_VZVirtioBlockDeviceConfiguration")]
#[path = "VZVirtioBlockDeviceConfiguration.rs"]
mod __VZVirtioBlockDeviceConfiguration;
#[cfg(feature = "Virtualization_VZVirtioConsoleDevice")]
#[path = "VZVirtioConsoleDevice.rs"]
mod __VZVirtioConsoleDevice;
#[cfg(feature = "Virtualization_VZVirtioConsoleDeviceConfiguration")]
#[path = "VZVirtioConsoleDeviceConfiguration.rs"]
mod __VZVirtioConsoleDeviceConfiguration;
#[cfg(feature = "Virtualization_VZVirtioConsoleDeviceSerialPortConfiguration")]
#[path = "VZVirtioConsoleDeviceSerialPortConfiguration.rs"]
mod __VZVirtioConsoleDeviceSerialPortConfiguration;
#[cfg(feature = "Virtualization_VZVirtioConsolePort")]
#[path = "VZVirtioConsolePort.rs"]
mod __VZVirtioConsolePort;
#[cfg(feature = "Virtualization_VZVirtioConsolePortArray")]
#[path = "VZVirtioConsolePortArray.rs"]
mod __VZVirtioConsolePortArray;
#[cfg(feature = "Virtualization_VZVirtioConsolePortConfiguration")]
#[path = "VZVirtioConsolePortConfiguration.rs"]
mod __VZVirtioConsolePortConfiguration;
#[cfg(feature = "Virtualization_VZVirtioConsolePortConfigurationArray")]
#[path = "VZVirtioConsolePortConfigurationArray.rs"]
mod __VZVirtioConsolePortConfigurationArray;
#[cfg(feature = "Virtualization_VZVirtioEntropyDeviceConfiguration")]
#[path = "VZVirtioEntropyDeviceConfiguration.rs"]
mod __VZVirtioEntropyDeviceConfiguration;
#[cfg(feature = "Virtualization_VZVirtioFileSystemDevice")]
#[path = "VZVirtioFileSystemDevice.rs"]
mod __VZVirtioFileSystemDevice;
#[cfg(feature = "Virtualization_VZVirtioFileSystemDeviceConfiguration")]
#[path = "VZVirtioFileSystemDeviceConfiguration.rs"]
mod __VZVirtioFileSystemDeviceConfiguration;
#[cfg(feature = "Virtualization_VZVirtioGraphicsDevice")]
#[path = "VZVirtioGraphicsDevice.rs"]
mod __VZVirtioGraphicsDevice;
#[cfg(feature = "Virtualization_VZVirtioGraphicsDeviceConfiguration")]
#[path = "VZVirtioGraphicsDeviceConfiguration.rs"]
mod __VZVirtioGraphicsDeviceConfiguration;
#[cfg(feature = "Virtualization_VZVirtioGraphicsScanout")]
#[path = "VZVirtioGraphicsScanout.rs"]
mod __VZVirtioGraphicsScanout;
#[cfg(feature = "Virtualization_VZVirtioGraphicsScanoutConfiguration")]
#[path = "VZVirtioGraphicsScanoutConfiguration.rs"]
mod __VZVirtioGraphicsScanoutConfiguration;
#[cfg(feature = "Virtualization_VZVirtioNetworkDeviceConfiguration")]
#[path = "VZVirtioNetworkDeviceConfiguration.rs"]
mod __VZVirtioNetworkDeviceConfiguration;
#[cfg(feature = "Virtualization_VZVirtioSocketConnection")]
#[path = "VZVirtioSocketConnection.rs"]
mod __VZVirtioSocketConnection;
#[cfg(feature = "Virtualization_VZVirtioSocketDevice")]
#[path = "VZVirtioSocketDevice.rs"]
mod __VZVirtioSocketDevice;
#[cfg(feature = "Virtualization_VZVirtioSocketDeviceConfiguration")]
#[path = "VZVirtioSocketDeviceConfiguration.rs"]
mod __VZVirtioSocketDeviceConfiguration;
#[cfg(feature = "Virtualization_VZVirtioSocketListener")]
#[path = "VZVirtioSocketListener.rs"]
mod __VZVirtioSocketListener;
#[cfg(feature = "Virtualization_VZVirtioSoundDeviceConfiguration")]
#[path = "VZVirtioSoundDeviceConfiguration.rs"]
mod __VZVirtioSoundDeviceConfiguration;
#[cfg(feature = "Virtualization_VZVirtioSoundDeviceInputStreamConfiguration")]
#[path = "VZVirtioSoundDeviceInputStreamConfiguration.rs"]
mod __VZVirtioSoundDeviceInputStreamConfiguration;
#[cfg(feature = "Virtualization_VZVirtioSoundDeviceOutputStreamConfiguration")]
#[path = "VZVirtioSoundDeviceOutputStreamConfiguration.rs"]
mod __VZVirtioSoundDeviceOutputStreamConfiguration;
#[cfg(feature = "Virtualization_VZVirtioSoundDeviceStreamConfiguration")]
#[path = "VZVirtioSoundDeviceStreamConfiguration.rs"]
mod __VZVirtioSoundDeviceStreamConfiguration;
#[cfg(feature = "Virtualization_VZVirtioTraditionalMemoryBalloonDevice")]
#[path = "VZVirtioTraditionalMemoryBalloonDevice.rs"]
mod __VZVirtioTraditionalMemoryBalloonDevice;
#[cfg(feature = "Virtualization_VZVirtioTraditionalMemoryBalloonDeviceConfiguration")]
#[path = "VZVirtioTraditionalMemoryBalloonDeviceConfiguration.rs"]
mod __VZVirtioTraditionalMemoryBalloonDeviceConfiguration;
#[cfg(feature = "Virtualization_VZVirtualMachine")]
#[path = "VZVirtualMachine.rs"]
mod __VZVirtualMachine;
#[cfg(feature = "Virtualization_VZVirtualMachineConfiguration")]
#[path = "VZVirtualMachineConfiguration.rs"]
mod __VZVirtualMachineConfiguration;
#[cfg(feature = "Virtualization_VZVirtualMachineDelegate")]
#[path = "VZVirtualMachineDelegate.rs"]
mod __VZVirtualMachineDelegate;
#[cfg(feature = "Virtualization_VZVirtualMachineStartOptions")]
#[path = "VZVirtualMachineStartOptions.rs"]
mod __VZVirtualMachineStartOptions;
#[cfg(feature = "Virtualization_VZVirtualMachineView")]
#[path = "VZVirtualMachineView.rs"]
mod __VZVirtualMachineView;

#[cfg(feature = "Virtualization_VZAudioDeviceConfiguration")]
pub use self::__VZAudioDeviceConfiguration::VZAudioDeviceConfiguration;
#[cfg(feature = "Virtualization_VZAudioInputStreamSource")]
pub use self::__VZAudioInputStreamSource::VZAudioInputStreamSource;
#[cfg(feature = "Virtualization_VZAudioOutputStreamSink")]
pub use self::__VZAudioOutputStreamSink::VZAudioOutputStreamSink;
#[cfg(feature = "Virtualization_VZBootLoader")]
pub use self::__VZBootLoader::VZBootLoader;
#[cfg(all(
    feature = "Virtualization_VZBridgedNetworkDeviceAttachment",
    feature = "Virtualization_VZNetworkDeviceAttachment"
))]
pub use self::__VZBridgedNetworkDeviceAttachment::VZBridgedNetworkDeviceAttachment;
#[cfg(feature = "Virtualization_VZBridgedNetworkInterface")]
pub use self::__VZBridgedNetworkInterface::VZBridgedNetworkInterface;
#[cfg(feature = "Virtualization_VZConsoleDevice")]
pub use self::__VZConsoleDevice::VZConsoleDevice;
#[cfg(feature = "Virtualization_VZConsoleDeviceConfiguration")]
pub use self::__VZConsoleDeviceConfiguration::VZConsoleDeviceConfiguration;
#[cfg(feature = "Virtualization_VZConsolePortConfiguration")]
pub use self::__VZConsolePortConfiguration::VZConsolePortConfiguration;
#[cfg(feature = "Virtualization_VZDirectoryShare")]
pub use self::__VZDirectoryShare::VZDirectoryShare;
#[cfg(feature = "Virtualization_VZDirectorySharingDevice")]
pub use self::__VZDirectorySharingDevice::VZDirectorySharingDevice;
#[cfg(feature = "Virtualization_VZDirectorySharingDeviceConfiguration")]
pub use self::__VZDirectorySharingDeviceConfiguration::VZDirectorySharingDeviceConfiguration;
#[cfg(all(
    feature = "Virtualization_VZDiskBlockDeviceStorageDeviceAttachment",
    feature = "Virtualization_VZStorageDeviceAttachment"
))]
pub use self::__VZDiskBlockDeviceStorageDeviceAttachment::VZDiskBlockDeviceStorageDeviceAttachment;
#[cfg(feature = "Virtualization_VZDiskImageStorageDeviceAttachment")]
pub use self::__VZDiskImageStorageDeviceAttachment::VZDiskImageCachingMode;
#[cfg(all(
    feature = "Virtualization_VZDiskImageStorageDeviceAttachment",
    feature = "Virtualization_VZStorageDeviceAttachment"
))]
pub use self::__VZDiskImageStorageDeviceAttachment::VZDiskImageStorageDeviceAttachment;
#[cfg(feature = "Virtualization_VZDiskImageStorageDeviceAttachment")]
pub use self::__VZDiskImageStorageDeviceAttachment::VZDiskImageSynchronizationMode;
#[cfg(feature = "Virtualization_VZDiskSynchronizationMode")]
pub use self::__VZDiskSynchronizationMode::VZDiskSynchronizationMode;
#[cfg(all(
    feature = "Virtualization_VZBootLoader",
    feature = "Virtualization_VZEFIBootLoader"
))]
pub use self::__VZEFIBootLoader::VZEFIBootLoader;
#[cfg(feature = "Virtualization_VZEFIVariableStore")]
pub use self::__VZEFIVariableStore::VZEFIVariableStore;
#[cfg(feature = "Virtualization_VZEFIVariableStore")]
pub use self::__VZEFIVariableStore::VZEFIVariableStoreInitializationOptions;
#[cfg(feature = "Virtualization_VZEntropyDeviceConfiguration")]
pub use self::__VZEntropyDeviceConfiguration::VZEntropyDeviceConfiguration;
#[cfg(feature = "Virtualization_VZError")]
pub use self::__VZError::VZErrorCode;
#[cfg(all(
    feature = "Foundation_NSError",
    feature = "Foundation_NSString",
    feature = "Virtualization_VZError"
))]
pub use self::__VZError::VZErrorDomain;
#[cfg(all(
    feature = "Virtualization_VZFileHandleNetworkDeviceAttachment",
    feature = "Virtualization_VZNetworkDeviceAttachment"
))]
pub use self::__VZFileHandleNetworkDeviceAttachment::VZFileHandleNetworkDeviceAttachment;
#[cfg(all(
    feature = "Virtualization_VZFileHandleSerialPortAttachment",
    feature = "Virtualization_VZSerialPortAttachment"
))]
pub use self::__VZFileHandleSerialPortAttachment::VZFileHandleSerialPortAttachment;
#[cfg(all(
    feature = "Virtualization_VZFileSerialPortAttachment",
    feature = "Virtualization_VZSerialPortAttachment"
))]
pub use self::__VZFileSerialPortAttachment::VZFileSerialPortAttachment;
#[cfg(feature = "Virtualization_VZGenericMachineIdentifier")]
pub use self::__VZGenericMachineIdentifier::VZGenericMachineIdentifier;
#[cfg(all(
    feature = "Virtualization_VZGenericPlatformConfiguration",
    feature = "Virtualization_VZPlatformConfiguration"
))]
pub use self::__VZGenericPlatformConfiguration::VZGenericPlatformConfiguration;
#[cfg(feature = "Virtualization_VZGraphicsDevice")]
pub use self::__VZGraphicsDevice::VZGraphicsDevice;
#[cfg(feature = "Virtualization_VZGraphicsDeviceConfiguration")]
pub use self::__VZGraphicsDeviceConfiguration::VZGraphicsDeviceConfiguration;
#[cfg(feature = "Virtualization_VZGraphicsDisplay")]
pub use self::__VZGraphicsDisplay::VZGraphicsDisplay;
#[cfg(feature = "Virtualization_VZGraphicsDisplay")]
pub use self::__VZGraphicsDisplay::VZGraphicsDisplayObserver;
#[cfg(feature = "Virtualization_VZGraphicsDisplayConfiguration")]
pub use self::__VZGraphicsDisplayConfiguration::VZGraphicsDisplayConfiguration;
#[cfg(all(
    feature = "Virtualization_VZAudioInputStreamSource",
    feature = "Virtualization_VZHostAudioInputStreamSource"
))]
pub use self::__VZHostAudioInputStreamSource::VZHostAudioInputStreamSource;
#[cfg(all(
    feature = "Virtualization_VZAudioOutputStreamSink",
    feature = "Virtualization_VZHostAudioOutputStreamSink"
))]
pub use self::__VZHostAudioOutputStreamSink::VZHostAudioOutputStreamSink;
#[cfg(feature = "Virtualization_VZKeyboardConfiguration")]
pub use self::__VZKeyboardConfiguration::VZKeyboardConfiguration;
#[cfg(all(
    feature = "Virtualization_VZBootLoader",
    feature = "Virtualization_VZLinuxBootLoader"
))]
pub use self::__VZLinuxBootLoader::VZLinuxBootLoader;
#[cfg(all(
    feature = "Virtualization_VZLinuxRosettaAbstractSocketCachingOptions",
    feature = "Virtualization_VZLinuxRosettaCachingOptions"
))]
pub use self::__VZLinuxRosettaAbstractSocketCachingOptions::VZLinuxRosettaAbstractSocketCachingOptions;
#[cfg(feature = "Virtualization_VZLinuxRosettaCachingOptions")]
pub use self::__VZLinuxRosettaCachingOptions::VZLinuxRosettaCachingOptions;
#[cfg(feature = "Virtualization_VZLinuxRosettaDirectoryShare")]
pub use self::__VZLinuxRosettaDirectoryShare::VZLinuxRosettaAvailability;
#[cfg(all(
    feature = "Virtualization_VZDirectoryShare",
    feature = "Virtualization_VZLinuxRosettaDirectoryShare"
))]
pub use self::__VZLinuxRosettaDirectoryShare::VZLinuxRosettaDirectoryShare;
#[cfg(all(
    feature = "Virtualization_VZLinuxRosettaCachingOptions",
    feature = "Virtualization_VZLinuxRosettaUnixSocketCachingOptions"
))]
pub use self::__VZLinuxRosettaUnixSocketCachingOptions::VZLinuxRosettaUnixSocketCachingOptions;
#[cfg(feature = "Virtualization_VZMACAddress")]
pub use self::__VZMACAddress::VZMACAddress;
#[cfg(feature = "Virtualization_VZMacAuxiliaryStorage")]
pub use self::__VZMacAuxiliaryStorage::VZMacAuxiliaryStorage;
#[cfg(feature = "Virtualization_VZMacAuxiliaryStorage")]
pub use self::__VZMacAuxiliaryStorage::VZMacAuxiliaryStorageInitializationOptions;
#[cfg(all(
    feature = "Virtualization_VZGraphicsDevice",
    feature = "Virtualization_VZMacGraphicsDevice"
))]
pub use self::__VZMacGraphicsDevice::VZMacGraphicsDevice;
#[cfg(all(
    feature = "Virtualization_VZGraphicsDeviceConfiguration",
    feature = "Virtualization_VZMacGraphicsDeviceConfiguration"
))]
pub use self::__VZMacGraphicsDeviceConfiguration::VZMacGraphicsDeviceConfiguration;
#[cfg(all(
    feature = "Virtualization_VZGraphicsDisplay",
    feature = "Virtualization_VZMacGraphicsDisplay"
))]
pub use self::__VZMacGraphicsDisplay::VZMacGraphicsDisplay;
#[cfg(all(
    feature = "Virtualization_VZGraphicsDisplayConfiguration",
    feature = "Virtualization_VZMacGraphicsDisplayConfiguration"
))]
pub use self::__VZMacGraphicsDisplayConfiguration::VZMacGraphicsDisplayConfiguration;
#[cfg(feature = "Virtualization_VZMacHardwareModel")]
pub use self::__VZMacHardwareModel::VZMacHardwareModel;
#[cfg(all(
    feature = "Virtualization_VZKeyboardConfiguration",
    feature = "Virtualization_VZMacKeyboardConfiguration"
))]
pub use self::__VZMacKeyboardConfiguration::VZMacKeyboardConfiguration;
#[cfg(feature = "Virtualization_VZMacMachineIdentifier")]
pub use self::__VZMacMachineIdentifier::VZMacMachineIdentifier;
#[cfg(all(
    feature = "Virtualization_VZBootLoader",
    feature = "Virtualization_VZMacOSBootLoader"
))]
pub use self::__VZMacOSBootLoader::VZMacOSBootLoader;
#[cfg(feature = "Virtualization_VZMacOSConfigurationRequirements")]
pub use self::__VZMacOSConfigurationRequirements::VZMacOSConfigurationRequirements;
#[cfg(feature = "Virtualization_VZMacOSInstaller")]
pub use self::__VZMacOSInstaller::VZMacOSInstaller;
#[cfg(feature = "Virtualization_VZMacOSRestoreImage")]
pub use self::__VZMacOSRestoreImage::VZMacOSRestoreImage;
#[cfg(all(
    feature = "Virtualization_VZMacOSVirtualMachineStartOptions",
    feature = "Virtualization_VZVirtualMachineStartOptions"
))]
pub use self::__VZMacOSVirtualMachineStartOptions::VZMacOSVirtualMachineStartOptions;
#[cfg(all(
    feature = "Virtualization_VZMacPlatformConfiguration",
    feature = "Virtualization_VZPlatformConfiguration"
))]
pub use self::__VZMacPlatformConfiguration::VZMacPlatformConfiguration;
#[cfg(all(
    feature = "Virtualization_VZMacTrackpadConfiguration",
    feature = "Virtualization_VZPointingDeviceConfiguration"
))]
pub use self::__VZMacTrackpadConfiguration::VZMacTrackpadConfiguration;
#[cfg(feature = "Virtualization_VZMemoryBalloonDevice")]
pub use self::__VZMemoryBalloonDevice::VZMemoryBalloonDevice;
#[cfg(feature = "Virtualization_VZMemoryBalloonDeviceConfiguration")]
pub use self::__VZMemoryBalloonDeviceConfiguration::VZMemoryBalloonDeviceConfiguration;
#[cfg(all(
    feature = "Virtualization_VZDirectoryShare",
    feature = "Virtualization_VZMultipleDirectoryShare"
))]
pub use self::__VZMultipleDirectoryShare::VZMultipleDirectoryShare;
#[cfg(all(
    feature = "Virtualization_VZNATNetworkDeviceAttachment",
    feature = "Virtualization_VZNetworkDeviceAttachment"
))]
pub use self::__VZNATNetworkDeviceAttachment::VZNATNetworkDeviceAttachment;
#[cfg(all(
    feature = "Virtualization_VZNVMExpressControllerDeviceConfiguration",
    feature = "Virtualization_VZStorageDeviceConfiguration"
))]
pub use self::__VZNVMExpressControllerDeviceConfiguration::VZNVMExpressControllerDeviceConfiguration;
#[cfg(all(
    feature = "Virtualization_VZNetworkBlockDeviceStorageDeviceAttachment",
    feature = "Virtualization_VZStorageDeviceAttachment"
))]
pub use self::__VZNetworkBlockDeviceStorageDeviceAttachment::VZNetworkBlockDeviceStorageDeviceAttachment;
#[cfg(feature = "Virtualization_VZNetworkBlockDeviceStorageDeviceAttachment")]
pub use self::__VZNetworkBlockDeviceStorageDeviceAttachment::VZNetworkBlockDeviceStorageDeviceAttachmentDelegate;
#[cfg(feature = "Virtualization_VZNetworkDevice")]
pub use self::__VZNetworkDevice::VZNetworkDevice;
#[cfg(feature = "Virtualization_VZNetworkDeviceAttachment")]
pub use self::__VZNetworkDeviceAttachment::VZNetworkDeviceAttachment;
#[cfg(feature = "Virtualization_VZNetworkDeviceConfiguration")]
pub use self::__VZNetworkDeviceConfiguration::VZNetworkDeviceConfiguration;
#[cfg(feature = "Virtualization_VZPlatformConfiguration")]
pub use self::__VZPlatformConfiguration::VZPlatformConfiguration;
#[cfg(feature = "Virtualization_VZPointingDeviceConfiguration")]
pub use self::__VZPointingDeviceConfiguration::VZPointingDeviceConfiguration;
#[cfg(feature = "Virtualization_VZSerialPortAttachment")]
pub use self::__VZSerialPortAttachment::VZSerialPortAttachment;
#[cfg(feature = "Virtualization_VZSerialPortConfiguration")]
pub use self::__VZSerialPortConfiguration::VZSerialPortConfiguration;
#[cfg(feature = "Virtualization_VZSharedDirectory")]
pub use self::__VZSharedDirectory::VZSharedDirectory;
#[cfg(all(
    feature = "Virtualization_VZDirectoryShare",
    feature = "Virtualization_VZSingleDirectoryShare"
))]
pub use self::__VZSingleDirectoryShare::VZSingleDirectoryShare;
#[cfg(feature = "Virtualization_VZSocketDevice")]
pub use self::__VZSocketDevice::VZSocketDevice;
#[cfg(feature = "Virtualization_VZSocketDeviceConfiguration")]
pub use self::__VZSocketDeviceConfiguration::VZSocketDeviceConfiguration;
#[cfg(all(
    feature = "Virtualization_VZSerialPortAttachment",
    feature = "Virtualization_VZSpiceAgentPortAttachment"
))]
pub use self::__VZSpiceAgentPortAttachment::VZSpiceAgentPortAttachment;
#[cfg(feature = "Virtualization_VZStorageDeviceAttachment")]
pub use self::__VZStorageDeviceAttachment::VZStorageDeviceAttachment;
#[cfg(feature = "Virtualization_VZStorageDeviceConfiguration")]
pub use self::__VZStorageDeviceConfiguration::VZStorageDeviceConfiguration;
#[cfg(all(
    feature = "Virtualization_VZKeyboardConfiguration",
    feature = "Virtualization_VZUSBKeyboardConfiguration"
))]
pub use self::__VZUSBKeyboardConfiguration::VZUSBKeyboardConfiguration;
#[cfg(all(
    feature = "Virtualization_VZStorageDeviceConfiguration",
    feature = "Virtualization_VZUSBMassStorageDeviceConfiguration"
))]
pub use self::__VZUSBMassStorageDeviceConfiguration::VZUSBMassStorageDeviceConfiguration;
#[cfg(all(
    feature = "Virtualization_VZPointingDeviceConfiguration",
    feature = "Virtualization_VZUSBScreenCoordinatePointingDeviceConfiguration"
))]
pub use self::__VZUSBScreenCoordinatePointingDeviceConfiguration::VZUSBScreenCoordinatePointingDeviceConfiguration;
#[cfg(all(
    feature = "Virtualization_VZStorageDeviceConfiguration",
    feature = "Virtualization_VZVirtioBlockDeviceConfiguration"
))]
pub use self::__VZVirtioBlockDeviceConfiguration::VZVirtioBlockDeviceConfiguration;
#[cfg(all(
    feature = "Virtualization_VZConsoleDevice",
    feature = "Virtualization_VZVirtioConsoleDevice"
))]
pub use self::__VZVirtioConsoleDevice::VZVirtioConsoleDevice;
#[cfg(feature = "Virtualization_VZVirtioConsoleDevice")]
pub use self::__VZVirtioConsoleDevice::VZVirtioConsoleDeviceDelegate;
#[cfg(all(
    feature = "Virtualization_VZConsoleDeviceConfiguration",
    feature = "Virtualization_VZVirtioConsoleDeviceConfiguration"
))]
pub use self::__VZVirtioConsoleDeviceConfiguration::VZVirtioConsoleDeviceConfiguration;
#[cfg(all(
    feature = "Virtualization_VZSerialPortConfiguration",
    feature = "Virtualization_VZVirtioConsoleDeviceSerialPortConfiguration"
))]
pub use self::__VZVirtioConsoleDeviceSerialPortConfiguration::VZVirtioConsoleDeviceSerialPortConfiguration;
#[cfg(feature = "Virtualization_VZVirtioConsolePort")]
pub use self::__VZVirtioConsolePort::VZVirtioConsolePort;
#[cfg(feature = "Virtualization_VZVirtioConsolePortArray")]
pub use self::__VZVirtioConsolePortArray::VZVirtioConsolePortArray;
#[cfg(all(
    feature = "Virtualization_VZConsolePortConfiguration",
    feature = "Virtualization_VZVirtioConsolePortConfiguration"
))]
pub use self::__VZVirtioConsolePortConfiguration::VZVirtioConsolePortConfiguration;
#[cfg(feature = "Virtualization_VZVirtioConsolePortConfigurationArray")]
pub use self::__VZVirtioConsolePortConfigurationArray::VZVirtioConsolePortConfigurationArray;
#[cfg(all(
    feature = "Virtualization_VZEntropyDeviceConfiguration",
    feature = "Virtualization_VZVirtioEntropyDeviceConfiguration"
))]
pub use self::__VZVirtioEntropyDeviceConfiguration::VZVirtioEntropyDeviceConfiguration;
#[cfg(all(
    feature = "Virtualization_VZDirectorySharingDevice",
    feature = "Virtualization_VZVirtioFileSystemDevice"
))]
pub use self::__VZVirtioFileSystemDevice::VZVirtioFileSystemDevice;
#[cfg(all(
    feature = "Virtualization_VZDirectorySharingDeviceConfiguration",
    feature = "Virtualization_VZVirtioFileSystemDeviceConfiguration"
))]
pub use self::__VZVirtioFileSystemDeviceConfiguration::VZVirtioFileSystemDeviceConfiguration;
#[cfg(all(
    feature = "Virtualization_VZGraphicsDevice",
    feature = "Virtualization_VZVirtioGraphicsDevice"
))]
pub use self::__VZVirtioGraphicsDevice::VZVirtioGraphicsDevice;
#[cfg(all(
    feature = "Virtualization_VZGraphicsDeviceConfiguration",
    feature = "Virtualization_VZVirtioGraphicsDeviceConfiguration"
))]
pub use self::__VZVirtioGraphicsDeviceConfiguration::VZVirtioGraphicsDeviceConfiguration;
#[cfg(all(
    feature = "Virtualization_VZGraphicsDisplay",
    feature = "Virtualization_VZVirtioGraphicsScanout"
))]
pub use self::__VZVirtioGraphicsScanout::VZVirtioGraphicsScanout;
#[cfg(all(
    feature = "Virtualization_VZGraphicsDisplayConfiguration",
    feature = "Virtualization_VZVirtioGraphicsScanoutConfiguration"
))]
pub use self::__VZVirtioGraphicsScanoutConfiguration::VZVirtioGraphicsScanoutConfiguration;
#[cfg(all(
    feature = "Virtualization_VZNetworkDeviceConfiguration",
    feature = "Virtualization_VZVirtioNetworkDeviceConfiguration"
))]
pub use self::__VZVirtioNetworkDeviceConfiguration::VZVirtioNetworkDeviceConfiguration;
#[cfg(feature = "Virtualization_VZVirtioSocketConnection")]
pub use self::__VZVirtioSocketConnection::VZVirtioSocketConnection;
#[cfg(all(
    feature = "Virtualization_VZSocketDevice",
    feature = "Virtualization_VZVirtioSocketDevice"
))]
pub use self::__VZVirtioSocketDevice::VZVirtioSocketDevice;
#[cfg(all(
    feature = "Virtualization_VZSocketDeviceConfiguration",
    feature = "Virtualization_VZVirtioSocketDeviceConfiguration"
))]
pub use self::__VZVirtioSocketDeviceConfiguration::VZVirtioSocketDeviceConfiguration;
#[cfg(feature = "Virtualization_VZVirtioSocketListener")]
pub use self::__VZVirtioSocketListener::VZVirtioSocketListener;
#[cfg(feature = "Virtualization_VZVirtioSocketListener")]
pub use self::__VZVirtioSocketListener::VZVirtioSocketListenerDelegate;
#[cfg(all(
    feature = "Virtualization_VZAudioDeviceConfiguration",
    feature = "Virtualization_VZVirtioSoundDeviceConfiguration"
))]
pub use self::__VZVirtioSoundDeviceConfiguration::VZVirtioSoundDeviceConfiguration;
#[cfg(all(
    feature = "Virtualization_VZVirtioSoundDeviceInputStreamConfiguration",
    feature = "Virtualization_VZVirtioSoundDeviceStreamConfiguration"
))]
pub use self::__VZVirtioSoundDeviceInputStreamConfiguration::VZVirtioSoundDeviceInputStreamConfiguration;
#[cfg(all(
    feature = "Virtualization_VZVirtioSoundDeviceOutputStreamConfiguration",
    feature = "Virtualization_VZVirtioSoundDeviceStreamConfiguration"
))]
pub use self::__VZVirtioSoundDeviceOutputStreamConfiguration::VZVirtioSoundDeviceOutputStreamConfiguration;
#[cfg(feature = "Virtualization_VZVirtioSoundDeviceStreamConfiguration")]
pub use self::__VZVirtioSoundDeviceStreamConfiguration::VZVirtioSoundDeviceStreamConfiguration;
#[cfg(all(
    feature = "Virtualization_VZMemoryBalloonDevice",
    feature = "Virtualization_VZVirtioTraditionalMemoryBalloonDevice"
))]
pub use self::__VZVirtioTraditionalMemoryBalloonDevice::VZVirtioTraditionalMemoryBalloonDevice;
#[cfg(all(
    feature = "Virtualization_VZMemoryBalloonDeviceConfiguration",
    feature = "Virtualization_VZVirtioTraditionalMemoryBalloonDeviceConfiguration"
))]
pub use self::__VZVirtioTraditionalMemoryBalloonDeviceConfiguration::VZVirtioTraditionalMemoryBalloonDeviceConfiguration;
#[cfg(feature = "Virtualization_VZVirtualMachine")]
pub use self::__VZVirtualMachine::VZVirtualMachine;
#[cfg(feature = "Virtualization_VZVirtualMachine")]
pub use self::__VZVirtualMachine::VZVirtualMachineState;
#[cfg(feature = "Virtualization_VZVirtualMachineConfiguration")]
pub use self::__VZVirtualMachineConfiguration::VZVirtualMachineConfiguration;
#[cfg(feature = "Virtualization_VZVirtualMachineDelegate")]
pub use self::__VZVirtualMachineDelegate::VZVirtualMachineDelegate;
#[cfg(feature = "Virtualization_VZVirtualMachineStartOptions")]
pub use self::__VZVirtualMachineStartOptions::VZVirtualMachineStartOptions;
#[cfg(all(
    feature = "AppKit_NSResponder",
    feature = "AppKit_NSView",
    feature = "Virtualization_VZVirtualMachineView"
))]
pub use self::__VZVirtualMachineView::VZVirtualMachineView;
