//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use crate::common::*;
use crate::AppKit::*;
use crate::Foundation::*;
use crate::Virtualization::*;

extern_class!(
    #[derive(Debug, PartialEq, Eq, Hash)]
    #[cfg(feature = "Virtualization_VZNetworkDeviceAttachment")]
    pub struct VZBridgedNetworkDeviceAttachment;

    #[cfg(feature = "Virtualization_VZNetworkDeviceAttachment")]
    unsafe impl ClassType for VZBridgedNetworkDeviceAttachment {
        #[inherits(NSObject)]
        type Super = VZNetworkDeviceAttachment;
        type Mutability = InteriorMutable;
    }
);

#[cfg(feature = "Virtualization_VZNetworkDeviceAttachment")]
unsafe impl NSObjectProtocol for VZBridgedNetworkDeviceAttachment {}

extern_methods!(
    #[cfg(feature = "Virtualization_VZNetworkDeviceAttachment")]
    unsafe impl VZBridgedNetworkDeviceAttachment {
        #[cfg(feature = "Virtualization_VZBridgedNetworkInterface")]
        #[method_id(@__retain_semantics Init initWithInterface:)]
        pub unsafe fn initWithInterface(
            this: Allocated<Self>,
            interface: &VZBridgedNetworkInterface,
        ) -> Id<Self>;

        #[cfg(feature = "Virtualization_VZBridgedNetworkInterface")]
        #[method_id(@__retain_semantics Other interface)]
        pub unsafe fn interface(&self) -> Id<VZBridgedNetworkInterface>;
    }
);

extern_methods!(
    /// Methods declared on superclass `VZNetworkDeviceAttachment`
    #[cfg(feature = "Virtualization_VZNetworkDeviceAttachment")]
    unsafe impl VZBridgedNetworkDeviceAttachment {
        #[method_id(@__retain_semantics New new)]
        pub unsafe fn new() -> Id<Self>;

        #[method_id(@__retain_semantics Init init)]
        pub unsafe fn init(this: Allocated<Self>) -> Id<Self>;
    }
);
