//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use crate::common::*;
use crate::AppKit::*;
use crate::Foundation::*;
use crate::Virtualization::*;

// NS_ENUM
#[repr(transparent)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct VZDiskSynchronizationMode(pub NSInteger);
impl VZDiskSynchronizationMode {
    #[doc(alias = "VZDiskSynchronizationModeFull")]
    pub const Full: Self = Self(0);
    #[doc(alias = "VZDiskSynchronizationModeNone")]
    pub const None: Self = Self(1);
}

#[cfg(feature = "objc2")]
unsafe impl Encode for VZDiskSynchronizationMode {
    const ENCODING: Encoding = NSInteger::ENCODING;
}

#[cfg(feature = "objc2")]
unsafe impl RefEncode for VZDiskSynchronizationMode {
    const ENCODING_REF: Encoding = Encoding::Pointer(&Self::ENCODING);
}
