//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use crate::common::*;
use crate::AppKit::*;
use crate::Foundation::*;
use crate::Virtualization::*;

extern_class!(
    #[derive(Debug, PartialEq, Eq, Hash)]
    #[cfg(feature = "Virtualization_VZBootLoader")]
    pub struct VZEFIBootLoader;

    #[cfg(feature = "Virtualization_VZBootLoader")]
    unsafe impl ClassType for VZEFIBootLoader {
        #[inherits(NSObject)]
        type Super = VZBootLoader;
        type Mutability = InteriorMutable;
    }
);

#[cfg(all(
    feature = "Foundation_NSObject",
    feature = "Virtualization_VZBootLoader"
))]
unsafe impl NSCopying for VZEFIBootLoader {}

#[cfg(feature = "Virtualization_VZBootLoader")]
unsafe impl NSObjectProtocol for VZEFIBootLoader {}

extern_methods!(
    #[cfg(feature = "Virtualization_VZBootLoader")]
    unsafe impl VZEFIBootLoader {
        #[method_id(@__retain_semantics Init init)]
        pub unsafe fn init(this: Allocated<Self>) -> Id<Self>;

        #[cfg(feature = "Virtualization_VZEFIVariableStore")]
        #[method_id(@__retain_semantics Other variableStore)]
        pub unsafe fn variableStore(&self) -> Option<Id<VZEFIVariableStore>>;

        #[cfg(feature = "Virtualization_VZEFIVariableStore")]
        #[method(setVariableStore:)]
        pub unsafe fn setVariableStore(&self, variable_store: Option<&VZEFIVariableStore>);
    }
);

extern_methods!(
    /// Methods declared on superclass `VZBootLoader`
    #[cfg(feature = "Virtualization_VZBootLoader")]
    unsafe impl VZEFIBootLoader {
        #[method_id(@__retain_semantics New new)]
        pub unsafe fn new() -> Id<Self>;
    }
);
