//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use crate::common::*;
use crate::AppKit::*;
use crate::Foundation::*;
use crate::Virtualization::*;

extern_class!(
    #[derive(Debug, PartialEq, Eq, Hash)]
    #[cfg(feature = "Virtualization_VZNetworkDeviceAttachment")]
    pub struct VZFileHandleNetworkDeviceAttachment;

    #[cfg(feature = "Virtualization_VZNetworkDeviceAttachment")]
    unsafe impl ClassType for VZFileHandleNetworkDeviceAttachment {
        #[inherits(NSObject)]
        type Super = VZNetworkDeviceAttachment;
        type Mutability = InteriorMutable;
    }
);

#[cfg(feature = "Virtualization_VZNetworkDeviceAttachment")]
unsafe impl NSObjectProtocol for VZFileHandleNetworkDeviceAttachment {}

extern_methods!(
    #[cfg(feature = "Virtualization_VZNetworkDeviceAttachment")]
    unsafe impl VZFileHandleNetworkDeviceAttachment {
        #[cfg(feature = "Foundation_NSFileHandle")]
        #[method_id(@__retain_semantics Init initWithFileHandle:)]
        pub unsafe fn initWithFileHandle(
            this: Allocated<Self>,
            file_handle: &NSFileHandle,
        ) -> Id<Self>;

        #[cfg(feature = "Foundation_NSFileHandle")]
        #[method_id(@__retain_semantics Other fileHandle)]
        pub unsafe fn fileHandle(&self) -> Id<NSFileHandle>;

        #[method(maximumTransmissionUnit)]
        pub unsafe fn maximumTransmissionUnit(&self) -> NSInteger;

        #[method(setMaximumTransmissionUnit:)]
        pub unsafe fn setMaximumTransmissionUnit(&self, maximum_transmission_unit: NSInteger);
    }
);

extern_methods!(
    /// Methods declared on superclass `VZNetworkDeviceAttachment`
    #[cfg(feature = "Virtualization_VZNetworkDeviceAttachment")]
    unsafe impl VZFileHandleNetworkDeviceAttachment {
        #[method_id(@__retain_semantics New new)]
        pub unsafe fn new() -> Id<Self>;

        #[method_id(@__retain_semantics Init init)]
        pub unsafe fn init(this: Allocated<Self>) -> Id<Self>;
    }
);
