//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use crate::common::*;
use crate::AppKit::*;
use crate::Foundation::*;
use crate::Virtualization::*;

extern_class!(
    #[derive(Debug, PartialEq, Eq, Hash)]
    #[cfg(feature = "Virtualization_VZAudioOutputStreamSink")]
    pub struct VZHostAudioOutputStreamSink;

    #[cfg(feature = "Virtualization_VZAudioOutputStreamSink")]
    unsafe impl ClassType for VZHostAudioOutputStreamSink {
        #[inherits(NSObject)]
        type Super = VZAudioOutputStreamSink;
        type Mutability = InteriorMutable;
    }
);

#[cfg(feature = "Virtualization_VZAudioOutputStreamSink")]
unsafe impl NSObjectProtocol for VZHostAudioOutputStreamSink {}

extern_methods!(
    #[cfg(feature = "Virtualization_VZAudioOutputStreamSink")]
    unsafe impl VZHostAudioOutputStreamSink {
        #[method_id(@__retain_semantics Init init)]
        pub unsafe fn init(this: Allocated<Self>) -> Id<Self>;
    }
);

extern_methods!(
    /// Methods declared on superclass `VZAudioOutputStreamSink`
    #[cfg(feature = "Virtualization_VZAudioOutputStreamSink")]
    unsafe impl VZHostAudioOutputStreamSink {
        #[method_id(@__retain_semantics New new)]
        pub unsafe fn new() -> Id<Self>;
    }
);
