//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use crate::common::*;
use crate::AppKit::*;
use crate::Foundation::*;
use crate::Virtualization::*;

extern_class!(
    #[derive(Debug, PartialEq, Eq, Hash)]
    #[cfg(feature = "Virtualization_VZAudioInputStreamSource")]
    pub struct VZHostAudioInputStreamSource;

    #[cfg(feature = "Virtualization_VZAudioInputStreamSource")]
    unsafe impl ClassType for VZHostAudioInputStreamSource {
        #[inherits(NSObject)]
        type Super = VZAudioInputStreamSource;
        type Mutability = InteriorMutable;
    }
);

#[cfg(feature = "Virtualization_VZAudioInputStreamSource")]
unsafe impl NSObjectProtocol for VZHostAudioInputStreamSource {}

extern_methods!(
    #[cfg(feature = "Virtualization_VZAudioInputStreamSource")]
    unsafe impl VZHostAudioInputStreamSource {
        #[method_id(@__retain_semantics Init init)]
        pub unsafe fn init(this: Allocated<Self>) -> Id<Self>;
    }
);

extern_methods!(
    /// Methods declared on superclass `VZAudioInputStreamSource`
    #[cfg(feature = "Virtualization_VZAudioInputStreamSource")]
    unsafe impl VZHostAudioInputStreamSource {
        #[method_id(@__retain_semantics New new)]
        pub unsafe fn new() -> Id<Self>;
    }
);
