//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use crate::common::*;
use crate::AppKit::*;
use crate::Foundation::*;
use crate::Virtualization::*;

extern_class!(
    #[derive(Debug, PartialEq, Eq, Hash)]
    #[cfg(feature = "Virtualization_VZLinuxRosettaCachingOptions")]
    pub struct VZLinuxRosettaUnixSocketCachingOptions;

    #[cfg(feature = "Virtualization_VZLinuxRosettaCachingOptions")]
    unsafe impl ClassType for VZLinuxRosettaUnixSocketCachingOptions {
        #[inherits(NSObject)]
        type Super = VZLinuxRosettaCachingOptions;
        type Mutability = InteriorMutable;
    }
);

#[cfg(feature = "Virtualization_VZLinuxRosettaCachingOptions")]
unsafe impl NSObjectProtocol for VZLinuxRosettaUnixSocketCachingOptions {}

extern_methods!(
    #[cfg(feature = "Virtualization_VZLinuxRosettaCachingOptions")]
    unsafe impl VZLinuxRosettaUnixSocketCachingOptions {
        #[cfg(all(feature = "Foundation_NSError", feature = "Foundation_NSString"))]
        #[method_id(@__retain_semantics Init initWithPath:error:_)]
        pub unsafe fn initWithPath_error(
            this: Allocated<Self>,
            path: &NSString,
        ) -> Result<Id<Self>, Id<NSError>>;

        #[method_id(@__retain_semantics Init init)]
        pub unsafe fn init(this: Allocated<Self>) -> Id<Self>;

        #[cfg(feature = "Foundation_NSString")]
        #[method_id(@__retain_semantics Other path)]
        pub unsafe fn path(&self) -> Id<NSString>;

        #[method(maximumPathLength)]
        pub unsafe fn maximumPathLength() -> NSUInteger;
    }
);

extern_methods!(
    /// Methods declared on superclass `VZLinuxRosettaCachingOptions`
    #[cfg(feature = "Virtualization_VZLinuxRosettaCachingOptions")]
    unsafe impl VZLinuxRosettaUnixSocketCachingOptions {
        #[method_id(@__retain_semantics New new)]
        pub unsafe fn new() -> Id<Self>;
    }
);
