//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use crate::common::*;
use crate::AppKit::*;
use crate::Foundation::*;
use crate::Virtualization::*;

extern_class!(
    #[derive(Debug, PartialEq, Eq, Hash)]
    pub struct VZMacOSConfigurationRequirements;

    unsafe impl ClassType for VZMacOSConfigurationRequirements {
        type Super = NSObject;
        type Mutability = InteriorMutable;
    }
);

unsafe impl NSObjectProtocol for VZMacOSConfigurationRequirements {}

extern_methods!(
    unsafe impl VZMacOSConfigurationRequirements {
        #[method_id(@__retain_semantics New new)]
        pub unsafe fn new() -> Id<Self>;

        #[method_id(@__retain_semantics Init init)]
        pub unsafe fn init(this: Allocated<Self>) -> Id<Self>;

        #[cfg(feature = "Virtualization_VZMacHardwareModel")]
        #[method_id(@__retain_semantics Other hardwareModel)]
        pub unsafe fn hardwareModel(&self) -> Id<VZMacHardwareModel>;

        #[method(minimumSupportedCPUCount)]
        pub unsafe fn minimumSupportedCPUCount(&self) -> NSUInteger;

        #[method(minimumSupportedMemorySize)]
        pub unsafe fn minimumSupportedMemorySize(&self) -> u64;
    }
);
