//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use crate::common::*;
use crate::AppKit::*;
use crate::Foundation::*;
use crate::Virtualization::*;

extern_class!(
    #[derive(Debug, PartialEq, Eq, Hash)]
    #[cfg(feature = "Virtualization_VZKeyboardConfiguration")]
    pub struct VZMacKeyboardConfiguration;

    #[cfg(feature = "Virtualization_VZKeyboardConfiguration")]
    unsafe impl ClassType for VZMacKeyboardConfiguration {
        #[inherits(NSObject)]
        type Super = VZKeyboardConfiguration;
        type Mutability = InteriorMutable;
    }
);

#[cfg(all(
    feature = "Foundation_NSObject",
    feature = "Virtualization_VZKeyboardConfiguration"
))]
unsafe impl NSCopying for VZMacKeyboardConfiguration {}

#[cfg(feature = "Virtualization_VZKeyboardConfiguration")]
unsafe impl NSObjectProtocol for VZMacKeyboardConfiguration {}

extern_methods!(
    #[cfg(feature = "Virtualization_VZKeyboardConfiguration")]
    unsafe impl VZMacKeyboardConfiguration {
        #[method_id(@__retain_semantics Init init)]
        pub unsafe fn init(this: Allocated<Self>) -> Id<Self>;
    }
);

extern_methods!(
    /// Methods declared on superclass `VZKeyboardConfiguration`
    #[cfg(feature = "Virtualization_VZKeyboardConfiguration")]
    unsafe impl VZMacKeyboardConfiguration {
        #[method_id(@__retain_semantics New new)]
        pub unsafe fn new() -> Id<Self>;
    }
);
