//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use crate::common::*;
use crate::AppKit::*;
use crate::Foundation::*;
use crate::Virtualization::*;

extern_class!(
    #[derive(Debug, PartialEq, Eq, Hash)]
    #[cfg(feature = "Virtualization_VZGraphicsDisplayConfiguration")]
    pub struct VZMacGraphicsDisplayConfiguration;

    #[cfg(feature = "Virtualization_VZGraphicsDisplayConfiguration")]
    unsafe impl ClassType for VZMacGraphicsDisplayConfiguration {
        #[inherits(NSObject)]
        type Super = VZGraphicsDisplayConfiguration;
        type Mutability = InteriorMutable;
    }
);

#[cfg(all(
    feature = "Foundation_NSObject",
    feature = "Virtualization_VZGraphicsDisplayConfiguration"
))]
unsafe impl NSCopying for VZMacGraphicsDisplayConfiguration {}

#[cfg(feature = "Virtualization_VZGraphicsDisplayConfiguration")]
unsafe impl NSObjectProtocol for VZMacGraphicsDisplayConfiguration {}

extern_methods!(
    #[cfg(feature = "Virtualization_VZGraphicsDisplayConfiguration")]
    unsafe impl VZMacGraphicsDisplayConfiguration {
        #[method_id(@__retain_semantics Init initWithWidthInPixels:heightInPixels:pixelsPerInch:)]
        pub unsafe fn initWithWidthInPixels_heightInPixels_pixelsPerInch(
            this: Allocated<Self>,
            width_in_pixels: NSInteger,
            height_in_pixels: NSInteger,
            pixels_per_inch: NSInteger,
        ) -> Id<Self>;

        #[cfg(all(feature = "AppKit_NSScreen", feature = "Foundation_NSGeometry"))]
        #[method_id(@__retain_semantics Init initForScreen:sizeInPoints:)]
        pub unsafe fn initForScreen_sizeInPoints(
            this: Allocated<Self>,
            screen: &NSScreen,
            size_in_points: NSSize,
        ) -> Id<Self>;

        #[method(widthInPixels)]
        pub unsafe fn widthInPixels(&self) -> NSInteger;

        #[method(setWidthInPixels:)]
        pub unsafe fn setWidthInPixels(&self, width_in_pixels: NSInteger);

        #[method(heightInPixels)]
        pub unsafe fn heightInPixels(&self) -> NSInteger;

        #[method(setHeightInPixels:)]
        pub unsafe fn setHeightInPixels(&self, height_in_pixels: NSInteger);

        #[method(pixelsPerInch)]
        pub unsafe fn pixelsPerInch(&self) -> NSInteger;

        #[method(setPixelsPerInch:)]
        pub unsafe fn setPixelsPerInch(&self, pixels_per_inch: NSInteger);
    }
);

extern_methods!(
    /// Methods declared on superclass `VZGraphicsDisplayConfiguration`
    #[cfg(feature = "Virtualization_VZGraphicsDisplayConfiguration")]
    unsafe impl VZMacGraphicsDisplayConfiguration {
        #[method_id(@__retain_semantics New new)]
        pub unsafe fn new() -> Id<Self>;

        #[method_id(@__retain_semantics Init init)]
        pub unsafe fn init(this: Allocated<Self>) -> Id<Self>;
    }
);
