//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use crate::common::*;
use crate::AppKit::*;
use crate::Foundation::*;
use crate::Virtualization::*;

extern_class!(
    #[derive(Debug, PartialEq, Eq, Hash)]
    pub struct VZMacOSInstaller;

    unsafe impl ClassType for VZMacOSInstaller {
        type Super = NSObject;
        type Mutability = InteriorMutable;
    }
);

unsafe impl NSObjectProtocol for VZMacOSInstaller {}

extern_methods!(
    unsafe impl VZMacOSInstaller {
        #[method_id(@__retain_semantics New new)]
        pub unsafe fn new() -> Id<Self>;

        #[method_id(@__retain_semantics Init init)]
        pub unsafe fn init(this: Allocated<Self>) -> Id<Self>;

        #[cfg(all(
            feature = "Foundation_NSURL",
            feature = "Virtualization_VZVirtualMachine"
        ))]
        #[method_id(@__retain_semantics Init initWithVirtualMachine:restoreImageURL:)]
        pub unsafe fn initWithVirtualMachine_restoreImageURL(
            this: Allocated<Self>,
            virtual_machine: &VZVirtualMachine,
            restore_image_file_url: &NSURL,
        ) -> Id<Self>;

        #[cfg(feature = "Foundation_NSError")]
        #[method(installWithCompletionHandler:)]
        pub unsafe fn installWithCompletionHandler(
            &self,
            completion_handler: &Block<dyn Fn(*mut NSError)>,
        );

        #[cfg(feature = "Foundation_NSProgress")]
        #[method_id(@__retain_semantics Other progress)]
        pub unsafe fn progress(&self) -> Id<NSProgress>;

        #[cfg(feature = "Virtualization_VZVirtualMachine")]
        #[method_id(@__retain_semantics Other virtualMachine)]
        pub unsafe fn virtualMachine(&self) -> Id<VZVirtualMachine>;

        #[cfg(feature = "Foundation_NSURL")]
        #[method_id(@__retain_semantics Other restoreImageURL)]
        pub unsafe fn restoreImageURL(&self) -> Id<NSURL>;
    }
);
