//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use crate::common::*;
use crate::AppKit::*;
use crate::Foundation::*;
use crate::Virtualization::*;

extern_class!(
    #[derive(Debug, PartialEq, Eq, Hash)]
    #[cfg(feature = "Virtualization_VZPointingDeviceConfiguration")]
    pub struct VZMacTrackpadConfiguration;

    #[cfg(feature = "Virtualization_VZPointingDeviceConfiguration")]
    unsafe impl ClassType for VZMacTrackpadConfiguration {
        #[inherits(NSObject)]
        type Super = VZPointingDeviceConfiguration;
        type Mutability = InteriorMutable;
    }
);

#[cfg(all(
    feature = "Foundation_NSObject",
    feature = "Virtualization_VZPointingDeviceConfiguration"
))]
unsafe impl NSCopying for VZMacTrackpadConfiguration {}

#[cfg(feature = "Virtualization_VZPointingDeviceConfiguration")]
unsafe impl NSObjectProtocol for VZMacTrackpadConfiguration {}

extern_methods!(
    #[cfg(feature = "Virtualization_VZPointingDeviceConfiguration")]
    unsafe impl VZMacTrackpadConfiguration {
        #[method_id(@__retain_semantics Init init)]
        pub unsafe fn init(this: Allocated<Self>) -> Id<Self>;
    }
);

extern_methods!(
    /// Methods declared on superclass `VZPointingDeviceConfiguration`
    #[cfg(feature = "Virtualization_VZPointingDeviceConfiguration")]
    unsafe impl VZMacTrackpadConfiguration {
        #[method_id(@__retain_semantics New new)]
        pub unsafe fn new() -> Id<Self>;
    }
);
