//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use crate::common::*;
use crate::AppKit::*;
use crate::Foundation::*;
use crate::Virtualization::*;

extern_class!(
    #[derive(Debug, PartialEq, Eq, Hash)]
    #[cfg(feature = "Virtualization_VZGraphicsDeviceConfiguration")]
    pub struct VZMacGraphicsDeviceConfiguration;

    #[cfg(feature = "Virtualization_VZGraphicsDeviceConfiguration")]
    unsafe impl ClassType for VZMacGraphicsDeviceConfiguration {
        #[inherits(NSObject)]
        type Super = VZGraphicsDeviceConfiguration;
        type Mutability = InteriorMutable;
    }
);

#[cfg(all(
    feature = "Foundation_NSObject",
    feature = "Virtualization_VZGraphicsDeviceConfiguration"
))]
unsafe impl NSCopying for VZMacGraphicsDeviceConfiguration {}

#[cfg(feature = "Virtualization_VZGraphicsDeviceConfiguration")]
unsafe impl NSObjectProtocol for VZMacGraphicsDeviceConfiguration {}

extern_methods!(
    #[cfg(feature = "Virtualization_VZGraphicsDeviceConfiguration")]
    unsafe impl VZMacGraphicsDeviceConfiguration {
        #[method_id(@__retain_semantics Init init)]
        pub unsafe fn init(this: Allocated<Self>) -> Id<Self>;

        #[cfg(all(
            feature = "Foundation_NSArray",
            feature = "Virtualization_VZGraphicsDisplayConfiguration",
            feature = "Virtualization_VZMacGraphicsDisplayConfiguration"
        ))]
        #[method_id(@__retain_semantics Other displays)]
        pub unsafe fn displays(&self) -> Id<NSArray<VZMacGraphicsDisplayConfiguration>>;

        #[cfg(all(
            feature = "Foundation_NSArray",
            feature = "Virtualization_VZGraphicsDisplayConfiguration",
            feature = "Virtualization_VZMacGraphicsDisplayConfiguration"
        ))]
        #[method(setDisplays:)]
        pub unsafe fn setDisplays(&self, displays: &NSArray<VZMacGraphicsDisplayConfiguration>);
    }
);

extern_methods!(
    /// Methods declared on superclass `VZGraphicsDeviceConfiguration`
    #[cfg(feature = "Virtualization_VZGraphicsDeviceConfiguration")]
    unsafe impl VZMacGraphicsDeviceConfiguration {
        #[method_id(@__retain_semantics New new)]
        pub unsafe fn new() -> Id<Self>;
    }
);
