//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use crate::common::*;
use crate::AppKit::*;
use crate::Foundation::*;
use crate::Virtualization::*;

extern_class!(
    #[derive(Debug, PartialEq, Eq, Hash)]
    #[cfg(feature = "Virtualization_VZBootLoader")]
    pub struct VZMacOSBootLoader;

    #[cfg(feature = "Virtualization_VZBootLoader")]
    unsafe impl ClassType for VZMacOSBootLoader {
        #[inherits(NSObject)]
        type Super = VZBootLoader;
        type Mutability = InteriorMutable;
    }
);

#[cfg(all(
    feature = "Foundation_NSObject",
    feature = "Virtualization_VZBootLoader"
))]
unsafe impl NSCopying for VZMacOSBootLoader {}

#[cfg(feature = "Virtualization_VZBootLoader")]
unsafe impl NSObjectProtocol for VZMacOSBootLoader {}

extern_methods!(
    #[cfg(feature = "Virtualization_VZBootLoader")]
    unsafe impl VZMacOSBootLoader {
        #[method_id(@__retain_semantics Init init)]
        pub unsafe fn init(this: Allocated<Self>) -> Id<Self>;
    }
);

extern_methods!(
    /// Methods declared on superclass `VZBootLoader`
    #[cfg(feature = "Virtualization_VZBootLoader")]
    unsafe impl VZMacOSBootLoader {
        #[method_id(@__retain_semantics New new)]
        pub unsafe fn new() -> Id<Self>;
    }
);
