//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use crate::common::*;
use crate::AppKit::*;
use crate::Foundation::*;
use crate::Virtualization::*;

extern_class!(
    #[derive(Debug, PartialEq, Eq, Hash)]
    pub struct VZNetworkDeviceConfiguration;

    unsafe impl ClassType for VZNetworkDeviceConfiguration {
        type Super = NSObject;
        type Mutability = InteriorMutable;
    }
);

#[cfg(feature = "Foundation_NSObject")]
unsafe impl NSCopying for VZNetworkDeviceConfiguration {}

unsafe impl NSObjectProtocol for VZNetworkDeviceConfiguration {}

extern_methods!(
    unsafe impl VZNetworkDeviceConfiguration {
        #[method_id(@__retain_semantics New new)]
        pub unsafe fn new() -> Id<Self>;

        #[method_id(@__retain_semantics Init init)]
        pub unsafe fn init(this: Allocated<Self>) -> Id<Self>;

        #[cfg(feature = "Virtualization_VZMACAddress")]
        #[method_id(@__retain_semantics Other MACAddress)]
        pub unsafe fn MACAddress(&self) -> Id<VZMACAddress>;

        #[cfg(feature = "Virtualization_VZMACAddress")]
        #[method(setMACAddress:)]
        pub unsafe fn setMACAddress(&self, mac_address: &VZMACAddress);

        #[cfg(feature = "Virtualization_VZNetworkDeviceAttachment")]
        #[method_id(@__retain_semantics Other attachment)]
        pub unsafe fn attachment(&self) -> Option<Id<VZNetworkDeviceAttachment>>;

        #[cfg(feature = "Virtualization_VZNetworkDeviceAttachment")]
        #[method(setAttachment:)]
        pub unsafe fn setAttachment(&self, attachment: Option<&VZNetworkDeviceAttachment>);
    }
);
