//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use crate::common::*;
use crate::AppKit::*;
use crate::Foundation::*;
use crate::Virtualization::*;

extern_class!(
    #[derive(Debug, PartialEq, Eq, Hash)]
    #[cfg(feature = "Virtualization_VZSerialPortAttachment")]
    pub struct VZSpiceAgentPortAttachment;

    #[cfg(feature = "Virtualization_VZSerialPortAttachment")]
    unsafe impl ClassType for VZSpiceAgentPortAttachment {
        #[inherits(NSObject)]
        type Super = VZSerialPortAttachment;
        type Mutability = InteriorMutable;
    }
);

#[cfg(feature = "Virtualization_VZSerialPortAttachment")]
unsafe impl NSObjectProtocol for VZSpiceAgentPortAttachment {}

extern_methods!(
    #[cfg(feature = "Virtualization_VZSerialPortAttachment")]
    unsafe impl VZSpiceAgentPortAttachment {
        #[method_id(@__retain_semantics Init init)]
        pub unsafe fn init(this: Allocated<Self>) -> Id<Self>;

        #[method(sharesClipboard)]
        pub unsafe fn sharesClipboard(&self) -> bool;

        #[method(setSharesClipboard:)]
        pub unsafe fn setSharesClipboard(&self, shares_clipboard: bool);

        #[cfg(feature = "Foundation_NSString")]
        #[method_id(@__retain_semantics Other spiceAgentPortName)]
        pub unsafe fn spiceAgentPortName() -> Id<NSString>;
    }
);

extern_methods!(
    /// Methods declared on superclass `VZSerialPortAttachment`
    #[cfg(feature = "Virtualization_VZSerialPortAttachment")]
    unsafe impl VZSpiceAgentPortAttachment {
        #[method_id(@__retain_semantics New new)]
        pub unsafe fn new() -> Id<Self>;
    }
);
