//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use crate::common::*;
use crate::AppKit::*;
use crate::Foundation::*;
use crate::Virtualization::*;

extern_class!(
    #[derive(Debug, PartialEq, Eq, Hash)]
    #[cfg(feature = "Virtualization_VZVirtioSoundDeviceStreamConfiguration")]
    pub struct VZVirtioSoundDeviceInputStreamConfiguration;

    #[cfg(feature = "Virtualization_VZVirtioSoundDeviceStreamConfiguration")]
    unsafe impl ClassType for VZVirtioSoundDeviceInputStreamConfiguration {
        #[inherits(NSObject)]
        type Super = VZVirtioSoundDeviceStreamConfiguration;
        type Mutability = InteriorMutable;
    }
);

#[cfg(all(
    feature = "Foundation_NSObject",
    feature = "Virtualization_VZVirtioSoundDeviceStreamConfiguration"
))]
unsafe impl NSCopying for VZVirtioSoundDeviceInputStreamConfiguration {}

#[cfg(feature = "Virtualization_VZVirtioSoundDeviceStreamConfiguration")]
unsafe impl NSObjectProtocol for VZVirtioSoundDeviceInputStreamConfiguration {}

extern_methods!(
    #[cfg(feature = "Virtualization_VZVirtioSoundDeviceStreamConfiguration")]
    unsafe impl VZVirtioSoundDeviceInputStreamConfiguration {
        #[method_id(@__retain_semantics Init init)]
        pub unsafe fn init(this: Allocated<Self>) -> Id<Self>;

        #[cfg(feature = "Virtualization_VZAudioInputStreamSource")]
        #[method_id(@__retain_semantics Other source)]
        pub unsafe fn source(&self) -> Option<Id<VZAudioInputStreamSource>>;

        #[cfg(feature = "Virtualization_VZAudioInputStreamSource")]
        #[method(setSource:)]
        pub unsafe fn setSource(&self, source: Option<&VZAudioInputStreamSource>);
    }
);

extern_methods!(
    /// Methods declared on superclass `VZVirtioSoundDeviceStreamConfiguration`
    #[cfg(feature = "Virtualization_VZVirtioSoundDeviceStreamConfiguration")]
    unsafe impl VZVirtioSoundDeviceInputStreamConfiguration {
        #[method_id(@__retain_semantics New new)]
        pub unsafe fn new() -> Id<Self>;
    }
);
