//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use crate::common::*;
use crate::AppKit::*;
use crate::Foundation::*;
use crate::Virtualization::*;

extern_class!(
    #[derive(Debug, PartialEq, Eq, Hash)]
    #[cfg(feature = "Virtualization_VZMemoryBalloonDevice")]
    pub struct VZVirtioTraditionalMemoryBalloonDevice;

    #[cfg(feature = "Virtualization_VZMemoryBalloonDevice")]
    unsafe impl ClassType for VZVirtioTraditionalMemoryBalloonDevice {
        #[inherits(NSObject)]
        type Super = VZMemoryBalloonDevice;
        type Mutability = InteriorMutable;
    }
);

#[cfg(feature = "Virtualization_VZMemoryBalloonDevice")]
unsafe impl NSObjectProtocol for VZVirtioTraditionalMemoryBalloonDevice {}

extern_methods!(
    #[cfg(feature = "Virtualization_VZMemoryBalloonDevice")]
    unsafe impl VZVirtioTraditionalMemoryBalloonDevice {
        #[method_id(@__retain_semantics New new)]
        pub unsafe fn new() -> Id<Self>;

        #[method_id(@__retain_semantics Init init)]
        pub unsafe fn init(this: Allocated<Self>) -> Id<Self>;

        #[method(targetVirtualMachineMemorySize)]
        pub unsafe fn targetVirtualMachineMemorySize(&self) -> u64;

        #[method(setTargetVirtualMachineMemorySize:)]
        pub unsafe fn setTargetVirtualMachineMemorySize(
            &self,
            target_virtual_machine_memory_size: u64,
        );
    }
);
