//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use crate::common::*;
use crate::AppKit::*;
use crate::Foundation::*;
use crate::Virtualization::*;

extern_class!(
    #[derive(Debug, PartialEq, Eq, Hash)]
    #[cfg(feature = "Virtualization_VZDirectorySharingDevice")]
    pub struct VZVirtioFileSystemDevice;

    #[cfg(feature = "Virtualization_VZDirectorySharingDevice")]
    unsafe impl ClassType for VZVirtioFileSystemDevice {
        #[inherits(NSObject)]
        type Super = VZDirectorySharingDevice;
        type Mutability = InteriorMutable;
    }
);

#[cfg(feature = "Virtualization_VZDirectorySharingDevice")]
unsafe impl NSObjectProtocol for VZVirtioFileSystemDevice {}

extern_methods!(
    #[cfg(feature = "Virtualization_VZDirectorySharingDevice")]
    unsafe impl VZVirtioFileSystemDevice {
        #[cfg(feature = "Foundation_NSString")]
        #[method_id(@__retain_semantics Other tag)]
        pub unsafe fn tag(&self) -> Id<NSString>;

        #[cfg(feature = "Virtualization_VZDirectoryShare")]
        #[method_id(@__retain_semantics Other share)]
        pub unsafe fn share(&self) -> Option<Id<VZDirectoryShare>>;

        #[cfg(feature = "Virtualization_VZDirectoryShare")]
        #[method(setShare:)]
        pub unsafe fn setShare(&self, share: Option<&VZDirectoryShare>);
    }
);

extern_methods!(
    /// Methods declared on superclass `VZDirectorySharingDevice`
    #[cfg(feature = "Virtualization_VZDirectorySharingDevice")]
    unsafe impl VZVirtioFileSystemDevice {
        #[method_id(@__retain_semantics New new)]
        pub unsafe fn new() -> Id<Self>;

        #[method_id(@__retain_semantics Init init)]
        pub unsafe fn init(this: Allocated<Self>) -> Id<Self>;
    }
);
