//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use crate::common::*;
use crate::AppKit::*;
use crate::Foundation::*;
use crate::Virtualization::*;

extern_class!(
    #[derive(Debug, PartialEq, Eq, Hash)]
    #[cfg(feature = "Virtualization_VZAudioDeviceConfiguration")]
    pub struct VZVirtioSoundDeviceConfiguration;

    #[cfg(feature = "Virtualization_VZAudioDeviceConfiguration")]
    unsafe impl ClassType for VZVirtioSoundDeviceConfiguration {
        #[inherits(NSObject)]
        type Super = VZAudioDeviceConfiguration;
        type Mutability = InteriorMutable;
    }
);

#[cfg(all(
    feature = "Foundation_NSObject",
    feature = "Virtualization_VZAudioDeviceConfiguration"
))]
unsafe impl NSCopying for VZVirtioSoundDeviceConfiguration {}

#[cfg(feature = "Virtualization_VZAudioDeviceConfiguration")]
unsafe impl NSObjectProtocol for VZVirtioSoundDeviceConfiguration {}

extern_methods!(
    #[cfg(feature = "Virtualization_VZAudioDeviceConfiguration")]
    unsafe impl VZVirtioSoundDeviceConfiguration {
        #[method_id(@__retain_semantics Init init)]
        pub unsafe fn init(this: Allocated<Self>) -> Id<Self>;

        #[cfg(all(
            feature = "Foundation_NSArray",
            feature = "Virtualization_VZVirtioSoundDeviceStreamConfiguration"
        ))]
        #[method_id(@__retain_semantics Other streams)]
        pub unsafe fn streams(&self) -> Id<NSArray<VZVirtioSoundDeviceStreamConfiguration>>;

        #[cfg(all(
            feature = "Foundation_NSArray",
            feature = "Virtualization_VZVirtioSoundDeviceStreamConfiguration"
        ))]
        #[method(setStreams:)]
        pub unsafe fn setStreams(&self, streams: &NSArray<VZVirtioSoundDeviceStreamConfiguration>);
    }
);

extern_methods!(
    /// Methods declared on superclass `VZAudioDeviceConfiguration`
    #[cfg(feature = "Virtualization_VZAudioDeviceConfiguration")]
    unsafe impl VZVirtioSoundDeviceConfiguration {
        #[method_id(@__retain_semantics New new)]
        pub unsafe fn new() -> Id<Self>;
    }
);
