//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use crate::common::*;
use crate::AppKit::*;
use crate::Foundation::*;
use crate::Virtualization::*;

extern_class!(
    #[derive(Debug, PartialEq, Eq, Hash)]
    pub struct VZVirtioSocketListener;

    unsafe impl ClassType for VZVirtioSocketListener {
        type Super = NSObject;
        type Mutability = InteriorMutable;
    }
);

unsafe impl NSObjectProtocol for VZVirtioSocketListener {}

extern_methods!(
    unsafe impl VZVirtioSocketListener {
        #[method_id(@__retain_semantics Other delegate)]
        pub unsafe fn delegate(
            &self,
        ) -> Option<Id<ProtocolObject<dyn VZVirtioSocketListenerDelegate>>>;

        #[method(setDelegate:)]
        pub unsafe fn setDelegate(
            &self,
            delegate: Option<&ProtocolObject<dyn VZVirtioSocketListenerDelegate>>,
        );
    }
);

extern_methods!(
    /// Methods declared on superclass `NSObject`
    unsafe impl VZVirtioSocketListener {
        #[method_id(@__retain_semantics Init init)]
        pub unsafe fn init(this: Allocated<Self>) -> Id<Self>;

        #[method_id(@__retain_semantics New new)]
        pub unsafe fn new() -> Id<Self>;
    }
);

extern_protocol!(
    pub unsafe trait VZVirtioSocketListenerDelegate: NSObjectProtocol {
        #[cfg(all(
            feature = "Virtualization_VZSocketDevice",
            feature = "Virtualization_VZVirtioSocketConnection",
            feature = "Virtualization_VZVirtioSocketDevice"
        ))]
        #[optional]
        #[method(listener:shouldAcceptNewConnection:fromSocketDevice:)]
        unsafe fn listener_shouldAcceptNewConnection_fromSocketDevice(
            &self,
            listener: &VZVirtioSocketListener,
            connection: &VZVirtioSocketConnection,
            socket_device: &VZVirtioSocketDevice,
        ) -> bool;
    }

    unsafe impl ProtocolType for dyn VZVirtioSocketListenerDelegate {}
);
