//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use crate::common::*;
use crate::AppKit::*;
use crate::Foundation::*;
use crate::Virtualization::*;

extern_class!(
    #[derive(Debug, PartialEq, Eq, Hash)]
    #[cfg(feature = "Virtualization_VZNetworkDeviceConfiguration")]
    pub struct VZVirtioNetworkDeviceConfiguration;

    #[cfg(feature = "Virtualization_VZNetworkDeviceConfiguration")]
    unsafe impl ClassType for VZVirtioNetworkDeviceConfiguration {
        #[inherits(NSObject)]
        type Super = VZNetworkDeviceConfiguration;
        type Mutability = InteriorMutable;
    }
);

#[cfg(all(
    feature = "Foundation_NSObject",
    feature = "Virtualization_VZNetworkDeviceConfiguration"
))]
unsafe impl NSCopying for VZVirtioNetworkDeviceConfiguration {}

#[cfg(feature = "Virtualization_VZNetworkDeviceConfiguration")]
unsafe impl NSObjectProtocol for VZVirtioNetworkDeviceConfiguration {}

extern_methods!(
    #[cfg(feature = "Virtualization_VZNetworkDeviceConfiguration")]
    unsafe impl VZVirtioNetworkDeviceConfiguration {
        #[method_id(@__retain_semantics Init init)]
        pub unsafe fn init(this: Allocated<Self>) -> Id<Self>;
    }
);

extern_methods!(
    /// Methods declared on superclass `VZNetworkDeviceConfiguration`
    #[cfg(feature = "Virtualization_VZNetworkDeviceConfiguration")]
    unsafe impl VZVirtioNetworkDeviceConfiguration {
        #[method_id(@__retain_semantics New new)]
        pub unsafe fn new() -> Id<Self>;
    }
);
