//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use crate::common::*;
use crate::AppKit::*;
use crate::Foundation::*;
use crate::Virtualization::*;

extern_class!(
    #[derive(Debug, PartialEq, Eq, Hash)]
    #[cfg(feature = "Virtualization_VZGraphicsDeviceConfiguration")]
    pub struct VZVirtioGraphicsDeviceConfiguration;

    #[cfg(feature = "Virtualization_VZGraphicsDeviceConfiguration")]
    unsafe impl ClassType for VZVirtioGraphicsDeviceConfiguration {
        #[inherits(NSObject)]
        type Super = VZGraphicsDeviceConfiguration;
        type Mutability = InteriorMutable;
    }
);

#[cfg(all(
    feature = "Foundation_NSObject",
    feature = "Virtualization_VZGraphicsDeviceConfiguration"
))]
unsafe impl NSCopying for VZVirtioGraphicsDeviceConfiguration {}

#[cfg(feature = "Virtualization_VZGraphicsDeviceConfiguration")]
unsafe impl NSObjectProtocol for VZVirtioGraphicsDeviceConfiguration {}

extern_methods!(
    #[cfg(feature = "Virtualization_VZGraphicsDeviceConfiguration")]
    unsafe impl VZVirtioGraphicsDeviceConfiguration {
        #[method_id(@__retain_semantics Init init)]
        pub unsafe fn init(this: Allocated<Self>) -> Id<Self>;

        #[cfg(all(
            feature = "Foundation_NSArray",
            feature = "Virtualization_VZGraphicsDisplayConfiguration",
            feature = "Virtualization_VZVirtioGraphicsScanoutConfiguration"
        ))]
        #[method_id(@__retain_semantics Other scanouts)]
        pub unsafe fn scanouts(&self) -> Id<NSArray<VZVirtioGraphicsScanoutConfiguration>>;

        #[cfg(all(
            feature = "Foundation_NSArray",
            feature = "Virtualization_VZGraphicsDisplayConfiguration",
            feature = "Virtualization_VZVirtioGraphicsScanoutConfiguration"
        ))]
        #[method(setScanouts:)]
        pub unsafe fn setScanouts(&self, scanouts: &NSArray<VZVirtioGraphicsScanoutConfiguration>);
    }
);

extern_methods!(
    /// Methods declared on superclass `VZGraphicsDeviceConfiguration`
    #[cfg(feature = "Virtualization_VZGraphicsDeviceConfiguration")]
    unsafe impl VZVirtioGraphicsDeviceConfiguration {
        #[method_id(@__retain_semantics New new)]
        pub unsafe fn new() -> Id<Self>;
    }
);
