//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use crate::common::*;
use crate::AppKit::*;
use crate::Foundation::*;
use crate::Virtualization::*;

extern_class!(
    #[derive(Debug, PartialEq, Eq, Hash)]
    #[cfg(feature = "Virtualization_VZGraphicsDisplay")]
    pub struct VZVirtioGraphicsScanout;

    #[cfg(feature = "Virtualization_VZGraphicsDisplay")]
    unsafe impl ClassType for VZVirtioGraphicsScanout {
        #[inherits(NSObject)]
        type Super = VZGraphicsDisplay;
        type Mutability = InteriorMutable;
    }
);

#[cfg(feature = "Virtualization_VZGraphicsDisplay")]
unsafe impl NSObjectProtocol for VZVirtioGraphicsScanout {}

extern_methods!(
    #[cfg(feature = "Virtualization_VZGraphicsDisplay")]
    unsafe impl VZVirtioGraphicsScanout {}
);

extern_methods!(
    /// Methods declared on superclass `VZGraphicsDisplay`
    #[cfg(feature = "Virtualization_VZGraphicsDisplay")]
    unsafe impl VZVirtioGraphicsScanout {
        #[method_id(@__retain_semantics New new)]
        pub unsafe fn new() -> Id<Self>;

        #[method_id(@__retain_semantics Init init)]
        pub unsafe fn init(this: Allocated<Self>) -> Id<Self>;
    }
);
