//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use crate::common::*;
use crate::AppKit::*;
use crate::Foundation::*;
use crate::Virtualization::*;

extern_class!(
    #[derive(Debug, PartialEq, Eq, Hash)]
    #[cfg(feature = "Virtualization_VZGraphicsDisplayConfiguration")]
    pub struct VZVirtioGraphicsScanoutConfiguration;

    #[cfg(feature = "Virtualization_VZGraphicsDisplayConfiguration")]
    unsafe impl ClassType for VZVirtioGraphicsScanoutConfiguration {
        #[inherits(NSObject)]
        type Super = VZGraphicsDisplayConfiguration;
        type Mutability = InteriorMutable;
    }
);

#[cfg(all(
    feature = "Foundation_NSObject",
    feature = "Virtualization_VZGraphicsDisplayConfiguration"
))]
unsafe impl NSCopying for VZVirtioGraphicsScanoutConfiguration {}

#[cfg(feature = "Virtualization_VZGraphicsDisplayConfiguration")]
unsafe impl NSObjectProtocol for VZVirtioGraphicsScanoutConfiguration {}

extern_methods!(
    #[cfg(feature = "Virtualization_VZGraphicsDisplayConfiguration")]
    unsafe impl VZVirtioGraphicsScanoutConfiguration {
        #[method_id(@__retain_semantics Init initWithWidthInPixels:heightInPixels:)]
        pub unsafe fn initWithWidthInPixels_heightInPixels(
            this: Allocated<Self>,
            width_in_pixels: NSInteger,
            height_in_pixels: NSInteger,
        ) -> Id<Self>;

        #[method(widthInPixels)]
        pub unsafe fn widthInPixels(&self) -> NSInteger;

        #[method(setWidthInPixels:)]
        pub unsafe fn setWidthInPixels(&self, width_in_pixels: NSInteger);

        #[method(heightInPixels)]
        pub unsafe fn heightInPixels(&self) -> NSInteger;

        #[method(setHeightInPixels:)]
        pub unsafe fn setHeightInPixels(&self, height_in_pixels: NSInteger);
    }
);

extern_methods!(
    /// Methods declared on superclass `VZGraphicsDisplayConfiguration`
    #[cfg(feature = "Virtualization_VZGraphicsDisplayConfiguration")]
    unsafe impl VZVirtioGraphicsScanoutConfiguration {
        #[method_id(@__retain_semantics New new)]
        pub unsafe fn new() -> Id<Self>;

        #[method_id(@__retain_semantics Init init)]
        pub unsafe fn init(this: Allocated<Self>) -> Id<Self>;
    }
);
