//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use crate::common::*;
use crate::AppKit::*;
use crate::Foundation::*;
use crate::Virtualization::*;

extern_class!(
    #[derive(Debug, PartialEq, Eq, Hash)]
    #[cfg(feature = "Virtualization_VZSerialPortConfiguration")]
    pub struct VZVirtioConsoleDeviceSerialPortConfiguration;

    #[cfg(feature = "Virtualization_VZSerialPortConfiguration")]
    unsafe impl ClassType for VZVirtioConsoleDeviceSerialPortConfiguration {
        #[inherits(NSObject)]
        type Super = VZSerialPortConfiguration;
        type Mutability = InteriorMutable;
    }
);

#[cfg(all(
    feature = "Foundation_NSObject",
    feature = "Virtualization_VZSerialPortConfiguration"
))]
unsafe impl NSCopying for VZVirtioConsoleDeviceSerialPortConfiguration {}

#[cfg(feature = "Virtualization_VZSerialPortConfiguration")]
unsafe impl NSObjectProtocol for VZVirtioConsoleDeviceSerialPortConfiguration {}

extern_methods!(
    #[cfg(feature = "Virtualization_VZSerialPortConfiguration")]
    unsafe impl VZVirtioConsoleDeviceSerialPortConfiguration {
        #[method_id(@__retain_semantics Init init)]
        pub unsafe fn init(this: Allocated<Self>) -> Id<Self>;
    }
);

extern_methods!(
    /// Methods declared on superclass `VZSerialPortConfiguration`
    #[cfg(feature = "Virtualization_VZSerialPortConfiguration")]
    unsafe impl VZVirtioConsoleDeviceSerialPortConfiguration {
        #[method_id(@__retain_semantics New new)]
        pub unsafe fn new() -> Id<Self>;
    }
);
