//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use crate::common::*;
use crate::AppKit::*;
use crate::Foundation::*;
use crate::Virtualization::*;

extern_class!(
    #[derive(Debug, PartialEq, Eq, Hash)]
    #[cfg(feature = "Virtualization_VZSocketDeviceConfiguration")]
    pub struct VZVirtioSocketDeviceConfiguration;

    #[cfg(feature = "Virtualization_VZSocketDeviceConfiguration")]
    unsafe impl ClassType for VZVirtioSocketDeviceConfiguration {
        #[inherits(NSObject)]
        type Super = VZSocketDeviceConfiguration;
        type Mutability = InteriorMutable;
    }
);

#[cfg(all(
    feature = "Foundation_NSObject",
    feature = "Virtualization_VZSocketDeviceConfiguration"
))]
unsafe impl NSCopying for VZVirtioSocketDeviceConfiguration {}

#[cfg(feature = "Virtualization_VZSocketDeviceConfiguration")]
unsafe impl NSObjectProtocol for VZVirtioSocketDeviceConfiguration {}

extern_methods!(
    #[cfg(feature = "Virtualization_VZSocketDeviceConfiguration")]
    unsafe impl VZVirtioSocketDeviceConfiguration {
        #[method_id(@__retain_semantics Init init)]
        pub unsafe fn init(this: Allocated<Self>) -> Id<Self>;
    }
);

extern_methods!(
    /// Methods declared on superclass `VZSocketDeviceConfiguration`
    #[cfg(feature = "Virtualization_VZSocketDeviceConfiguration")]
    unsafe impl VZVirtioSocketDeviceConfiguration {
        #[method_id(@__retain_semantics New new)]
        pub unsafe fn new() -> Id<Self>;
    }
);
