//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use crate::common::*;
use crate::AppKit::*;
use crate::Foundation::*;
use crate::Virtualization::*;

extern_class!(
    #[derive(Debug, PartialEq, Eq, Hash)]
    #[cfg(feature = "Virtualization_VZStorageDeviceConfiguration")]
    pub struct VZVirtioBlockDeviceConfiguration;

    #[cfg(feature = "Virtualization_VZStorageDeviceConfiguration")]
    unsafe impl ClassType for VZVirtioBlockDeviceConfiguration {
        #[inherits(NSObject)]
        type Super = VZStorageDeviceConfiguration;
        type Mutability = InteriorMutable;
    }
);

#[cfg(all(
    feature = "Foundation_NSObject",
    feature = "Virtualization_VZStorageDeviceConfiguration"
))]
unsafe impl NSCopying for VZVirtioBlockDeviceConfiguration {}

#[cfg(feature = "Virtualization_VZStorageDeviceConfiguration")]
unsafe impl NSObjectProtocol for VZVirtioBlockDeviceConfiguration {}

extern_methods!(
    #[cfg(feature = "Virtualization_VZStorageDeviceConfiguration")]
    unsafe impl VZVirtioBlockDeviceConfiguration {
        #[cfg(feature = "Virtualization_VZStorageDeviceAttachment")]
        #[method_id(@__retain_semantics Init initWithAttachment:)]
        pub unsafe fn initWithAttachment(
            this: Allocated<Self>,
            attachment: &VZStorageDeviceAttachment,
        ) -> Id<Self>;

        #[cfg(all(feature = "Foundation_NSError", feature = "Foundation_NSString"))]
        #[method(validateBlockDeviceIdentifier:error:_)]
        pub unsafe fn validateBlockDeviceIdentifier_error(
            block_device_identifier: &NSString,
        ) -> Result<(), Id<NSError>>;

        #[cfg(feature = "Foundation_NSString")]
        #[method_id(@__retain_semantics Other blockDeviceIdentifier)]
        pub unsafe fn blockDeviceIdentifier(&self) -> Id<NSString>;

        #[cfg(feature = "Foundation_NSString")]
        #[method(setBlockDeviceIdentifier:)]
        pub unsafe fn setBlockDeviceIdentifier(&self, block_device_identifier: &NSString);
    }
);

extern_methods!(
    /// Methods declared on superclass `VZStorageDeviceConfiguration`
    #[cfg(feature = "Virtualization_VZStorageDeviceConfiguration")]
    unsafe impl VZVirtioBlockDeviceConfiguration {
        #[method_id(@__retain_semantics New new)]
        pub unsafe fn new() -> Id<Self>;

        #[method_id(@__retain_semantics Init init)]
        pub unsafe fn init(this: Allocated<Self>) -> Id<Self>;
    }
);
