//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use crate::common::*;
use crate::AppKit::*;
use crate::Foundation::*;
use crate::Virtualization::*;

extern_class!(
    #[derive(Debug, PartialEq, Eq, Hash)]
    #[cfg(feature = "Virtualization_VZDirectorySharingDeviceConfiguration")]
    pub struct VZVirtioFileSystemDeviceConfiguration;

    #[cfg(feature = "Virtualization_VZDirectorySharingDeviceConfiguration")]
    unsafe impl ClassType for VZVirtioFileSystemDeviceConfiguration {
        #[inherits(NSObject)]
        type Super = VZDirectorySharingDeviceConfiguration;
        type Mutability = InteriorMutable;
    }
);

#[cfg(all(
    feature = "Foundation_NSObject",
    feature = "Virtualization_VZDirectorySharingDeviceConfiguration"
))]
unsafe impl NSCopying for VZVirtioFileSystemDeviceConfiguration {}

#[cfg(feature = "Virtualization_VZDirectorySharingDeviceConfiguration")]
unsafe impl NSObjectProtocol for VZVirtioFileSystemDeviceConfiguration {}

extern_methods!(
    #[cfg(feature = "Virtualization_VZDirectorySharingDeviceConfiguration")]
    unsafe impl VZVirtioFileSystemDeviceConfiguration {
        #[cfg(feature = "Foundation_NSString")]
        #[method_id(@__retain_semantics Init initWithTag:)]
        pub unsafe fn initWithTag(this: Allocated<Self>, tag: &NSString) -> Id<Self>;

        #[cfg(all(feature = "Foundation_NSError", feature = "Foundation_NSString"))]
        #[method(validateTag:error:_)]
        pub unsafe fn validateTag_error(tag: &NSString) -> Result<(), Id<NSError>>;

        #[cfg(feature = "Foundation_NSString")]
        #[method_id(@__retain_semantics Other tag)]
        pub unsafe fn tag(&self) -> Id<NSString>;

        #[cfg(feature = "Foundation_NSString")]
        #[method(setTag:)]
        pub unsafe fn setTag(&self, tag: &NSString);

        #[cfg(feature = "Virtualization_VZDirectoryShare")]
        #[method_id(@__retain_semantics Other share)]
        pub unsafe fn share(&self) -> Option<Id<VZDirectoryShare>>;

        #[cfg(feature = "Virtualization_VZDirectoryShare")]
        #[method(setShare:)]
        pub unsafe fn setShare(&self, share: Option<&VZDirectoryShare>);

        #[cfg(feature = "Foundation_NSString")]
        #[method_id(@__retain_semantics Other macOSGuestAutomountTag)]
        pub unsafe fn macOSGuestAutomountTag() -> Id<NSString>;
    }
);

extern_methods!(
    /// Methods declared on superclass `VZDirectorySharingDeviceConfiguration`
    #[cfg(feature = "Virtualization_VZDirectorySharingDeviceConfiguration")]
    unsafe impl VZVirtioFileSystemDeviceConfiguration {
        #[method_id(@__retain_semantics New new)]
        pub unsafe fn new() -> Id<Self>;

        #[method_id(@__retain_semantics Init init)]
        pub unsafe fn init(this: Allocated<Self>) -> Id<Self>;
    }
);
