//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use crate::common::*;
use crate::AppKit::*;
use crate::Foundation::*;
use crate::Virtualization::*;

extern_class!(
    #[derive(Debug, PartialEq, Eq, Hash)]
    pub struct VZVirtioConsolePortConfigurationArray;

    unsafe impl ClassType for VZVirtioConsolePortConfigurationArray {
        type Super = NSObject;
        type Mutability = InteriorMutable;
    }
);

#[cfg(feature = "Foundation_NSObject")]
unsafe impl NSCopying for VZVirtioConsolePortConfigurationArray {}

unsafe impl NSObjectProtocol for VZVirtioConsolePortConfigurationArray {}

extern_methods!(
    unsafe impl VZVirtioConsolePortConfigurationArray {
        #[method_id(@__retain_semantics New new)]
        pub unsafe fn new() -> Id<Self>;

        #[method_id(@__retain_semantics Init init)]
        pub unsafe fn init(this: Allocated<Self>) -> Id<Self>;

        #[method(maximumPortCount)]
        pub unsafe fn maximumPortCount(&self) -> u32;

        #[method(setMaximumPortCount:)]
        pub unsafe fn setMaximumPortCount(&self, maximum_port_count: u32);

        #[cfg(all(
            feature = "Virtualization_VZConsolePortConfiguration",
            feature = "Virtualization_VZVirtioConsolePortConfiguration"
        ))]
        #[method_id(@__retain_semantics Other objectAtIndexedSubscript:)]
        pub unsafe fn objectAtIndexedSubscript(
            &self,
            port_index: NSUInteger,
        ) -> Option<Id<VZVirtioConsolePortConfiguration>>;

        #[cfg(all(
            feature = "Virtualization_VZConsolePortConfiguration",
            feature = "Virtualization_VZVirtioConsolePortConfiguration"
        ))]
        #[method(setObject:atIndexedSubscript:)]
        pub unsafe fn setObject_atIndexedSubscript(
            &self,
            configuration: Option<&VZVirtioConsolePortConfiguration>,
            port_index: NSUInteger,
        );
    }
);
