//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use crate::common::*;
use crate::AppKit::*;
use crate::Foundation::*;
use crate::Virtualization::*;

extern_class!(
    #[derive(Debug, PartialEq, Eq, Hash)]
    pub struct VZVirtualMachineConfiguration;

    unsafe impl ClassType for VZVirtualMachineConfiguration {
        type Super = NSObject;
        type Mutability = InteriorMutable;
    }
);

#[cfg(feature = "Foundation_NSObject")]
unsafe impl NSCopying for VZVirtualMachineConfiguration {}

unsafe impl NSObjectProtocol for VZVirtualMachineConfiguration {}

extern_methods!(
    unsafe impl VZVirtualMachineConfiguration {
        #[cfg(feature = "Virtualization_VZBootLoader")]
        #[method_id(@__retain_semantics Other bootLoader)]
        pub unsafe fn bootLoader(&self) -> Option<Id<VZBootLoader>>;

        #[cfg(feature = "Virtualization_VZBootLoader")]
        #[method(setBootLoader:)]
        pub unsafe fn setBootLoader(&self, boot_loader: Option<&VZBootLoader>);

        #[method(memorySize)]
        pub unsafe fn memorySize(&self) -> u64;

        #[method(setMemorySize:)]
        pub unsafe fn setMemorySize(&self, memory_size: u64);

        #[method(CPUCount)]
        pub unsafe fn CPUCount(&self) -> NSUInteger;

        #[method(setCPUCount:)]
        pub unsafe fn setCPUCount(&self, cpu_count: NSUInteger);

        #[cfg(feature = "Virtualization_VZPlatformConfiguration")]
        #[method_id(@__retain_semantics Other platform)]
        pub unsafe fn platform(&self) -> Id<VZPlatformConfiguration>;

        #[cfg(feature = "Virtualization_VZPlatformConfiguration")]
        #[method(setPlatform:)]
        pub unsafe fn setPlatform(&self, platform: &VZPlatformConfiguration);

        #[cfg(all(
            feature = "Foundation_NSArray",
            feature = "Virtualization_VZAudioDeviceConfiguration"
        ))]
        #[method_id(@__retain_semantics Other audioDevices)]
        pub unsafe fn audioDevices(&self) -> Id<NSArray<VZAudioDeviceConfiguration>>;

        #[cfg(all(
            feature = "Foundation_NSArray",
            feature = "Virtualization_VZAudioDeviceConfiguration"
        ))]
        #[method(setAudioDevices:)]
        pub unsafe fn setAudioDevices(&self, audio_devices: &NSArray<VZAudioDeviceConfiguration>);

        #[cfg(all(
            feature = "Foundation_NSArray",
            feature = "Virtualization_VZConsoleDeviceConfiguration"
        ))]
        #[method_id(@__retain_semantics Other consoleDevices)]
        pub unsafe fn consoleDevices(&self) -> Id<NSArray<VZConsoleDeviceConfiguration>>;

        #[cfg(all(
            feature = "Foundation_NSArray",
            feature = "Virtualization_VZConsoleDeviceConfiguration"
        ))]
        #[method(setConsoleDevices:)]
        pub unsafe fn setConsoleDevices(
            &self,
            console_devices: &NSArray<VZConsoleDeviceConfiguration>,
        );

        #[cfg(all(
            feature = "Foundation_NSArray",
            feature = "Virtualization_VZDirectorySharingDeviceConfiguration"
        ))]
        #[method_id(@__retain_semantics Other directorySharingDevices)]
        pub unsafe fn directorySharingDevices(
            &self,
        ) -> Id<NSArray<VZDirectorySharingDeviceConfiguration>>;

        #[cfg(all(
            feature = "Foundation_NSArray",
            feature = "Virtualization_VZDirectorySharingDeviceConfiguration"
        ))]
        #[method(setDirectorySharingDevices:)]
        pub unsafe fn setDirectorySharingDevices(
            &self,
            directory_sharing_devices: &NSArray<VZDirectorySharingDeviceConfiguration>,
        );

        #[cfg(all(
            feature = "Foundation_NSArray",
            feature = "Virtualization_VZEntropyDeviceConfiguration"
        ))]
        #[method_id(@__retain_semantics Other entropyDevices)]
        pub unsafe fn entropyDevices(&self) -> Id<NSArray<VZEntropyDeviceConfiguration>>;

        #[cfg(all(
            feature = "Foundation_NSArray",
            feature = "Virtualization_VZEntropyDeviceConfiguration"
        ))]
        #[method(setEntropyDevices:)]
        pub unsafe fn setEntropyDevices(
            &self,
            entropy_devices: &NSArray<VZEntropyDeviceConfiguration>,
        );

        #[cfg(all(
            feature = "Foundation_NSArray",
            feature = "Virtualization_VZMemoryBalloonDeviceConfiguration"
        ))]
        #[method_id(@__retain_semantics Other memoryBalloonDevices)]
        pub unsafe fn memoryBalloonDevices(
            &self,
        ) -> Id<NSArray<VZMemoryBalloonDeviceConfiguration>>;

        #[cfg(all(
            feature = "Foundation_NSArray",
            feature = "Virtualization_VZMemoryBalloonDeviceConfiguration"
        ))]
        #[method(setMemoryBalloonDevices:)]
        pub unsafe fn setMemoryBalloonDevices(
            &self,
            memory_balloon_devices: &NSArray<VZMemoryBalloonDeviceConfiguration>,
        );

        #[cfg(all(
            feature = "Foundation_NSArray",
            feature = "Virtualization_VZNetworkDeviceConfiguration"
        ))]
        #[method_id(@__retain_semantics Other networkDevices)]
        pub unsafe fn networkDevices(&self) -> Id<NSArray<VZNetworkDeviceConfiguration>>;

        #[cfg(all(
            feature = "Foundation_NSArray",
            feature = "Virtualization_VZNetworkDeviceConfiguration"
        ))]
        #[method(setNetworkDevices:)]
        pub unsafe fn setNetworkDevices(
            &self,
            network_devices: &NSArray<VZNetworkDeviceConfiguration>,
        );

        #[cfg(all(
            feature = "Foundation_NSArray",
            feature = "Virtualization_VZSerialPortConfiguration"
        ))]
        #[method_id(@__retain_semantics Other serialPorts)]
        pub unsafe fn serialPorts(&self) -> Id<NSArray<VZSerialPortConfiguration>>;

        #[cfg(all(
            feature = "Foundation_NSArray",
            feature = "Virtualization_VZSerialPortConfiguration"
        ))]
        #[method(setSerialPorts:)]
        pub unsafe fn setSerialPorts(&self, serial_ports: &NSArray<VZSerialPortConfiguration>);

        #[cfg(all(
            feature = "Foundation_NSArray",
            feature = "Virtualization_VZSocketDeviceConfiguration"
        ))]
        #[method_id(@__retain_semantics Other socketDevices)]
        pub unsafe fn socketDevices(&self) -> Id<NSArray<VZSocketDeviceConfiguration>>;

        #[cfg(all(
            feature = "Foundation_NSArray",
            feature = "Virtualization_VZSocketDeviceConfiguration"
        ))]
        #[method(setSocketDevices:)]
        pub unsafe fn setSocketDevices(
            &self,
            socket_devices: &NSArray<VZSocketDeviceConfiguration>,
        );

        #[cfg(all(
            feature = "Foundation_NSArray",
            feature = "Virtualization_VZStorageDeviceConfiguration"
        ))]
        #[method_id(@__retain_semantics Other storageDevices)]
        pub unsafe fn storageDevices(&self) -> Id<NSArray<VZStorageDeviceConfiguration>>;

        #[cfg(all(
            feature = "Foundation_NSArray",
            feature = "Virtualization_VZStorageDeviceConfiguration"
        ))]
        #[method(setStorageDevices:)]
        pub unsafe fn setStorageDevices(
            &self,
            storage_devices: &NSArray<VZStorageDeviceConfiguration>,
        );

        #[cfg(all(
            feature = "Foundation_NSArray",
            feature = "Virtualization_VZKeyboardConfiguration"
        ))]
        #[method_id(@__retain_semantics Other keyboards)]
        pub unsafe fn keyboards(&self) -> Id<NSArray<VZKeyboardConfiguration>>;

        #[cfg(all(
            feature = "Foundation_NSArray",
            feature = "Virtualization_VZKeyboardConfiguration"
        ))]
        #[method(setKeyboards:)]
        pub unsafe fn setKeyboards(&self, keyboards: &NSArray<VZKeyboardConfiguration>);

        #[cfg(all(
            feature = "Foundation_NSArray",
            feature = "Virtualization_VZPointingDeviceConfiguration"
        ))]
        #[method_id(@__retain_semantics Other pointingDevices)]
        pub unsafe fn pointingDevices(&self) -> Id<NSArray<VZPointingDeviceConfiguration>>;

        #[cfg(all(
            feature = "Foundation_NSArray",
            feature = "Virtualization_VZPointingDeviceConfiguration"
        ))]
        #[method(setPointingDevices:)]
        pub unsafe fn setPointingDevices(
            &self,
            pointing_devices: &NSArray<VZPointingDeviceConfiguration>,
        );

        #[cfg(all(
            feature = "Foundation_NSArray",
            feature = "Virtualization_VZGraphicsDeviceConfiguration"
        ))]
        #[method_id(@__retain_semantics Other graphicsDevices)]
        pub unsafe fn graphicsDevices(&self) -> Id<NSArray<VZGraphicsDeviceConfiguration>>;

        #[cfg(all(
            feature = "Foundation_NSArray",
            feature = "Virtualization_VZGraphicsDeviceConfiguration"
        ))]
        #[method(setGraphicsDevices:)]
        pub unsafe fn setGraphicsDevices(
            &self,
            graphics_devices: &NSArray<VZGraphicsDeviceConfiguration>,
        );
    }
);

extern_methods!(
    /// Methods declared on superclass `NSObject`
    unsafe impl VZVirtualMachineConfiguration {
        #[method_id(@__retain_semantics Init init)]
        pub unsafe fn init(this: Allocated<Self>) -> Id<Self>;

        #[method_id(@__retain_semantics New new)]
        pub unsafe fn new() -> Id<Self>;
    }
);

extern_methods!(
    /// VZVirtualMachineConfigurationValidation
    unsafe impl VZVirtualMachineConfiguration {
        #[cfg(feature = "Foundation_NSError")]
        #[method(validateWithError:_)]
        pub unsafe fn validateWithError(&self) -> Result<(), Id<NSError>>;

        #[cfg(feature = "Foundation_NSError")]
        #[method(validateSaveRestoreSupportWithError:_)]
        pub unsafe fn validateSaveRestoreSupportWithError(&self) -> Result<(), Id<NSError>>;

        #[method(minimumAllowedMemorySize)]
        pub unsafe fn minimumAllowedMemorySize() -> u64;

        #[method(maximumAllowedMemorySize)]
        pub unsafe fn maximumAllowedMemorySize() -> u64;

        #[method(minimumAllowedCPUCount)]
        pub unsafe fn minimumAllowedCPUCount() -> NSUInteger;

        #[method(maximumAllowedCPUCount)]
        pub unsafe fn maximumAllowedCPUCount() -> NSUInteger;
    }
);
