//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use crate::common::*;
use crate::AppKit::*;
use crate::Foundation::*;
use crate::Virtualization::*;

extern_class!(
    #[derive(Debug, PartialEq, Eq, Hash)]
    #[cfg(feature = "Virtualization_VZVirtioSoundDeviceStreamConfiguration")]
    pub struct VZVirtioSoundDeviceOutputStreamConfiguration;

    #[cfg(feature = "Virtualization_VZVirtioSoundDeviceStreamConfiguration")]
    unsafe impl ClassType for VZVirtioSoundDeviceOutputStreamConfiguration {
        #[inherits(NSObject)]
        type Super = VZVirtioSoundDeviceStreamConfiguration;
        type Mutability = InteriorMutable;
    }
);

#[cfg(all(
    feature = "Foundation_NSObject",
    feature = "Virtualization_VZVirtioSoundDeviceStreamConfiguration"
))]
unsafe impl NSCopying for VZVirtioSoundDeviceOutputStreamConfiguration {}

#[cfg(feature = "Virtualization_VZVirtioSoundDeviceStreamConfiguration")]
unsafe impl NSObjectProtocol for VZVirtioSoundDeviceOutputStreamConfiguration {}

extern_methods!(
    #[cfg(feature = "Virtualization_VZVirtioSoundDeviceStreamConfiguration")]
    unsafe impl VZVirtioSoundDeviceOutputStreamConfiguration {
        #[method_id(@__retain_semantics Init init)]
        pub unsafe fn init(this: Allocated<Self>) -> Id<Self>;

        #[cfg(feature = "Virtualization_VZAudioOutputStreamSink")]
        #[method_id(@__retain_semantics Other sink)]
        pub unsafe fn sink(&self) -> Option<Id<VZAudioOutputStreamSink>>;

        #[cfg(feature = "Virtualization_VZAudioOutputStreamSink")]
        #[method(setSink:)]
        pub unsafe fn setSink(&self, sink: Option<&VZAudioOutputStreamSink>);
    }
);

extern_methods!(
    /// Methods declared on superclass `VZVirtioSoundDeviceStreamConfiguration`
    #[cfg(feature = "Virtualization_VZVirtioSoundDeviceStreamConfiguration")]
    unsafe impl VZVirtioSoundDeviceOutputStreamConfiguration {
        #[method_id(@__retain_semantics New new)]
        pub unsafe fn new() -> Id<Self>;
    }
);
