//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use crate::common::*;
use crate::AppKit::*;
use crate::Foundation::*;
use crate::Virtualization::*;

extern_class!(
    #[derive(Debug, PartialEq, Eq, Hash)]
    #[cfg(feature = "Virtualization_VZEntropyDeviceConfiguration")]
    pub struct VZVirtioEntropyDeviceConfiguration;

    #[cfg(feature = "Virtualization_VZEntropyDeviceConfiguration")]
    unsafe impl ClassType for VZVirtioEntropyDeviceConfiguration {
        #[inherits(NSObject)]
        type Super = VZEntropyDeviceConfiguration;
        type Mutability = InteriorMutable;
    }
);

#[cfg(all(
    feature = "Foundation_NSObject",
    feature = "Virtualization_VZEntropyDeviceConfiguration"
))]
unsafe impl NSCopying for VZVirtioEntropyDeviceConfiguration {}

#[cfg(feature = "Virtualization_VZEntropyDeviceConfiguration")]
unsafe impl NSObjectProtocol for VZVirtioEntropyDeviceConfiguration {}

extern_methods!(
    #[cfg(feature = "Virtualization_VZEntropyDeviceConfiguration")]
    unsafe impl VZVirtioEntropyDeviceConfiguration {
        #[method_id(@__retain_semantics Init init)]
        pub unsafe fn init(this: Allocated<Self>) -> Id<Self>;
    }
);

extern_methods!(
    /// Methods declared on superclass `VZEntropyDeviceConfiguration`
    #[cfg(feature = "Virtualization_VZEntropyDeviceConfiguration")]
    unsafe impl VZVirtioEntropyDeviceConfiguration {
        #[method_id(@__retain_semantics New new)]
        pub unsafe fn new() -> Id<Self>;
    }
);
