//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use crate::common::*;
use crate::AppKit::*;
use crate::Foundation::*;
use crate::Virtualization::*;

extern_class!(
    #[derive(Debug, PartialEq, Eq, Hash)]
    #[cfg(feature = "Virtualization_VZSocketDevice")]
    pub struct VZVirtioSocketDevice;

    #[cfg(feature = "Virtualization_VZSocketDevice")]
    unsafe impl ClassType for VZVirtioSocketDevice {
        #[inherits(NSObject)]
        type Super = VZSocketDevice;
        type Mutability = InteriorMutable;
    }
);

#[cfg(feature = "Virtualization_VZSocketDevice")]
unsafe impl NSObjectProtocol for VZVirtioSocketDevice {}

extern_methods!(
    #[cfg(feature = "Virtualization_VZSocketDevice")]
    unsafe impl VZVirtioSocketDevice {
        #[method_id(@__retain_semantics New new)]
        pub unsafe fn new() -> Id<Self>;

        #[method_id(@__retain_semantics Init init)]
        pub unsafe fn init(this: Allocated<Self>) -> Id<Self>;

        #[cfg(feature = "Virtualization_VZVirtioSocketListener")]
        #[method(setSocketListener:forPort:)]
        pub unsafe fn setSocketListener_forPort(
            &self,
            listener: &VZVirtioSocketListener,
            port: u32,
        );

        #[method(removeSocketListenerForPort:)]
        pub unsafe fn removeSocketListenerForPort(&self, port: u32);

        #[cfg(all(
            feature = "Foundation_NSError",
            feature = "Virtualization_VZVirtioSocketConnection"
        ))]
        #[method(connectToPort:completionHandler:)]
        pub unsafe fn connectToPort_completionHandler(
            &self,
            port: u32,
            completion_handler: &Block<dyn Fn(*mut VZVirtioSocketConnection, *mut NSError)>,
        );
    }
);
