//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use crate::common::*;
use crate::AppKit::*;
use crate::Foundation::*;
use crate::Virtualization::*;

extern_class!(
    #[derive(Debug, PartialEq, Eq, Hash)]
    #[cfg(feature = "Virtualization_VZConsoleDeviceConfiguration")]
    pub struct VZVirtioConsoleDeviceConfiguration;

    #[cfg(feature = "Virtualization_VZConsoleDeviceConfiguration")]
    unsafe impl ClassType for VZVirtioConsoleDeviceConfiguration {
        #[inherits(NSObject)]
        type Super = VZConsoleDeviceConfiguration;
        type Mutability = InteriorMutable;
    }
);

#[cfg(all(
    feature = "Foundation_NSObject",
    feature = "Virtualization_VZConsoleDeviceConfiguration"
))]
unsafe impl NSCopying for VZVirtioConsoleDeviceConfiguration {}

#[cfg(feature = "Virtualization_VZConsoleDeviceConfiguration")]
unsafe impl NSObjectProtocol for VZVirtioConsoleDeviceConfiguration {}

extern_methods!(
    #[cfg(feature = "Virtualization_VZConsoleDeviceConfiguration")]
    unsafe impl VZVirtioConsoleDeviceConfiguration {
        #[method_id(@__retain_semantics Init init)]
        pub unsafe fn init(this: Allocated<Self>) -> Id<Self>;

        #[cfg(feature = "Virtualization_VZVirtioConsolePortConfigurationArray")]
        #[method_id(@__retain_semantics Other ports)]
        pub unsafe fn ports(&self) -> Id<VZVirtioConsolePortConfigurationArray>;
    }
);

extern_methods!(
    /// Methods declared on superclass `VZConsoleDeviceConfiguration`
    #[cfg(feature = "Virtualization_VZConsoleDeviceConfiguration")]
    unsafe impl VZVirtioConsoleDeviceConfiguration {
        #[method_id(@__retain_semantics New new)]
        pub unsafe fn new() -> Id<Self>;
    }
);
